# frozen_string_literal: true

require_relative "lib/oapi/version"

Gem::Specification.new do |spec|
  spec.name     = "oapi-runtime"
  spec.version  = Oapi::VERSION
  spec.authors  = ["Jack Robertson"]
  spec.email    = ["jack.robertson@nexusmods.com"]

  spec.summary     = "Runtime support for code generated by the oapi OpenAPI generator."
  spec.description = "What oapi-generated Ruby code requires at runtime: the codecs that " \
                     "translate between wire values and Ruby types, the decoding primitives " \
                     "the generated structs are built from, and the credential extraction " \
                     "that a generated authenticator interface hands you."
  spec.homepage      = "https://github.com/Nexus-Mods/oapi"
  spec.license       = "MIT"
  spec.required_ruby_version = ">= 3.4"

  spec.metadata["rubygems_mfa_required"] = "true"
  spec.metadata["source_code_uri"]       = spec.homepage

  spec.files = Dir[
    "lib/oapi-runtime.rb",
    "lib/oapi/runtime.rb",
    "lib/oapi/{body,codec,decode,errors,form,optional,response,security,version,wire}.rb",
    "lib/oapi/codec/*.rb",
    "LICENSE.txt",
    "README.md"
  ]
  spec.require_paths = ["lib"]

  spec.add_dependency "actionpack", ">= 7.1"
  spec.add_dependency "bigdecimal", "~> 4.0"
  spec.add_dependency "sorbet-runtime", "~> 0.5"
end
