# frozen_string_literal: true

require_relative "lib/oapi/version"

Gem::Specification.new do |spec|
  spec.name     = "oapi-runtime"
  spec.version  = Oapi::VERSION
  spec.authors  = ["Jack Robertson"]
  spec.email    = ["jack.robertson@nexusmods.com"]

  spec.summary     = "Runtime support for code generated by the oapi OpenAPI generator."
  spec.description = "The small, dependency-light library that oapi-generated Ruby code " \
                     "requires at runtime: decoding primitives, the Codable protocol, " \
                     "request/response plumbing and schema validation."
  spec.homepage      = "https://github.com/Nexus-Mods/oapi"
  spec.license       = "MIT"
  spec.required_ruby_version = ">= 3.3"

  spec.metadata["rubygems_mfa_required"] = "true"
  spec.metadata["source_code_uri"]       = spec.homepage

  spec.files = Dir[
    "lib/oapi-runtime.rb",
    "lib/oapi/runtime.rb",
    "lib/oapi/{codec,container,decode,errors,optional,rails,version}.rb",
    "lib/oapi/rails/railtie.rb",
    "LICENSE.txt",
    "README.md"
  ]
  spec.require_paths = ["lib"]

  spec.add_dependency "actionpack", ">= 7.1"
  spec.add_dependency "bigdecimal", "~> 4.0"
  spec.add_dependency "railties", ">= 7.1"
  spec.add_dependency "sorbet-runtime", "~> 0.5"
end
