# frozen_string_literal: true

require_relative "lib/openapi_kit/version"

Gem::Specification.new do |spec|
  spec.name     = "openapi_kit"
  spec.version  = OpenAPIKit::VERSION
  spec.authors  = ["Jack Robertson"]
  spec.email    = ["jack.robertson@nexusmods.com"]

  spec.summary     = "Runtime support for code generated by the openapi_kit OpenAPI generator."
  spec.description = "What openapi_kit-generated Ruby code requires at runtime: the codecs that " \
                     "translate between wire values and Ruby types, the decoding primitives " \
                     "the generated structs are built from, and the credential extraction " \
                     "that a generated authenticator interface hands you."
  spec.homepage      = "https://github.com/Nexus-Mods/openapi_kit"
  spec.license       = "MIT"
  spec.required_ruby_version = ">= 3.4"

  spec.metadata["rubygems_mfa_required"] = "true"
  spec.metadata["source_code_uri"]       = spec.homepage

  spec.files = Dir[
    "lib/openapi_kit.rb",
    "lib/openapi_kit/runtime.rb",
    "lib/openapi_kit/{body,codec,decode,errors,form,optional,rendering,response,security,version,wire}.rb",
    "lib/openapi_kit/codec/*.rb",
    "LICENSE.txt",
    "README.md"
  ]
  spec.require_paths = ["lib"]

  spec.add_dependency "actionpack", ">= 8.0"
  spec.add_dependency "bigdecimal", "~> 4.0"
  spec.add_dependency "sorbet-runtime", "~> 0.5"
end
