# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Types
    class Mod < T::Struct
      extend T::Sig

      const :id, ::Integer
      const :name, ::String
      const :status, T.nilable(Server::Types::ModStatus)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(Mod) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      class Codec
        extend T::Sig
        extend T::Generic
        include ::Oapi::Codec

        Value = type_member { { fixed: Server::Types::Mod } }

        sig { override.params(value: T.untyped).returns(Server::Types::Mod) }
        def from_wire(value)
          raw = ::Oapi::Decode.object(value)
          Server::Types::Mod.new(
            id: ::Oapi::Decode.field(raw, "id") { |v| ::Oapi::Codec::Primitive::Integer::CODEC.from_wire(v) },
            name: ::Oapi::Decode.field(raw, "name") { |v| ::Oapi::Codec::Primitive::String::CODEC.from_wire(v) },
            status: ::Oapi::Decode.optional(raw, "status") { |v| Server::Types::ModStatus::CODEC.from_wire(v) },
          )
        end

        sig { override.params(value: Server::Types::Mod).returns(::Oapi::Wire) }
        def to_wire(value)
          wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
          wire["id"] = ::Oapi::Codec::Primitive::Integer::CODEC.to_wire(value.id)
          wire["name"] = ::Oapi::Codec::Primitive::String::CODEC.to_wire(value.name)
          status = value.status
          wire["status"] = Server::Types::ModStatus::CODEC.to_wire(status) unless status.nil?
          wire
        end
      end

      CODEC = T.let(Codec.new, Codec)
    end
  end
end
