# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module Server
  module Types
    class ModStatus < T::Enum
      enums do
        Live = new("live")
        Hidden = new("hidden")
      end

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::OpenAPIKit::Codec::Contract

        Value = type_template { { fixed: Server::Types::ModStatus } }

        sig { override.params(value: ::OpenAPIKit::Wire).returns(Server::Types::ModStatus) }
        def self.from_wire(value) = ::OpenAPIKit::Decode.enum(Server::Types::ModStatus, value)

        sig { override.params(value: Server::Types::ModStatus).returns(::OpenAPIKit::Wire) }
        def self.to_wire(value) = value.serialize
      end
    end
  end
end
