# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Types
    class ModStatus < T::Enum
      enums do
        Live = new("live")
        Hidden = new("hidden")
      end
    end
  end
end
