# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Types
    class NewMod < T::Struct
      extend T::Sig

      const :name, ::String

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(NewMod) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::Oapi::Codec::Contract

        Value = type_template { { fixed: Server::Types::NewMod } }

        sig { override.params(value: ::Oapi::Wire).returns(Server::Types::NewMod) }
        def self.from_wire(value)
          raw = ::Oapi::Decode.object(value)
          Server::Types::NewMod.new(
            name: ::Oapi::Decode.required(raw, "name") { |v| ::Oapi::Codec::String.from_wire(v) },
          )
        end

        sig { override.params(value: Server::Types::NewMod).returns(::Oapi::Wire) }
        def self.to_wire(value)
          wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
          wire["name"] = ::Oapi::Codec::String.to_wire(value.name)
          wire
        end
      end
    end
  end
end
