# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Types
    class NewMod < T::Struct
      extend T::Sig

      const :name, ::String

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(NewMod) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash
    end
  end
end
