# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module Server
  module Types
    class ProblemDetails < T::Struct
      extend T::Sig

      const :title, ::String
      const :detail, T.nilable(::String)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(ProblemDetails) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::OpenAPIKit::Codec::Contract

        Value = type_template { { fixed: Server::Types::ProblemDetails } }

        sig { override.params(value: ::OpenAPIKit::Wire).returns(Server::Types::ProblemDetails) }
        def self.from_wire(value)
          raw = ::OpenAPIKit::Decode.object(value)
          Server::Types::ProblemDetails.new(
            title: ::OpenAPIKit::Decode.required(raw, "title") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
            detail: ::OpenAPIKit::Decode.optional(raw, "detail") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
          )
        end

        sig { override.params(value: Server::Types::ProblemDetails).returns(::OpenAPIKit::Wire) }
        def self.to_wire(value)
          wire = T.let({}, T::Hash[::String, ::OpenAPIKit::Wire])
          wire["title"] = ::OpenAPIKit::Codec::String.to_wire(value.title)
          field = value.detail
          wire["detail"] = ::OpenAPIKit::Codec::String.to_wire(field) unless field.nil?
          wire
        end
      end
    end
  end
end
