# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Types
    class ProblemDetails < T::Struct
      extend T::Sig

      const :title, ::String
      const :detail, T.nilable(::String)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(ProblemDetails) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      class Codec
        extend T::Sig
        extend T::Generic
        include ::Oapi::Codec::Contract

        Value = type_member { { fixed: Server::Types::ProblemDetails } }

        sig { override.params(value: T.untyped).returns(Server::Types::ProblemDetails) }
        def from_wire(value)
          raw = ::Oapi::Decode.object(value)
          Server::Types::ProblemDetails.new(
            title: ::Oapi::Decode.field(raw, "title") { |v| ::Oapi::Codec::String::CODEC.from_wire(v) },
            detail: ::Oapi::Decode.optional(raw, "detail") { |v| ::Oapi::Codec::String::CODEC.from_wire(v) },
          )
        end

        sig { override.params(value: Server::Types::ProblemDetails).returns(::Oapi::Wire) }
        def to_wire(value)
          wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
          wire["title"] = ::Oapi::Codec::String::CODEC.to_wire(value.title)
          detail = value.detail
          wire["detail"] = ::Oapi::Codec::String::CODEC.to_wire(detail) unless detail.nil?
          wire
        end
      end

      CODEC = T.let(Codec.new, Codec)
    end
  end
end
