# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Types
    class UploadModFileBody < T::Struct
      extend T::Sig

      const :upload, ::ActionDispatch::Http::UploadedFile
      const :thumbnail, T.nilable(::ActionDispatch::Http::UploadedFile)
      const :description, T.nilable(::String)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(UploadModFileBody) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      module Form
        extend T::Sig
        extend T::Generic
        extend ::Oapi::Form::Contract

        Value = type_template { { fixed: Server::Types::UploadModFileBody } }

        sig { override.params(parts: ::Oapi::Form::Parts).returns(Server::Types::UploadModFileBody) }
        def self.from_parts(parts)
          Server::Types::UploadModFileBody.new(
            upload: ::Oapi::Decode.required(parts, "upload") { |v| ::Oapi::Decode.file(v) },
            thumbnail: ::Oapi::Decode.optional(parts, "thumbnail") { |v| ::Oapi::Decode.file(v) },
            description: ::Oapi::Decode.optional(parts, "description") { |v| ::Oapi::Codec::String.from_wire(v) },
          )
        end
      end
    end
  end
end
