# typed: strict
# frozen_string_literal: true

require "openapi_kit/runtime"

require "openapi_kit/codegen/naming"
require "openapi_kit/codegen/ruby_type"
require "openapi_kit/codegen/model/schema"
require "openapi_kit/codegen/model/type_def"
require "openapi_kit/codegen/model/document"
require "openapi_kit/codegen/type_registry"
require "openapi_kit/codegen/config"
require "openapi_kit/codegen/writer"
require "openapi_kit/codegen/loader"
require "openapi_kit/codegen/emit/buffer"
require "openapi_kit/codegen/emit/source_file"
require "openapi_kit/codegen/emit/emitter"
require "openapi_kit/codegen/emit/literal"
require "openapi_kit/codegen/emit/defaults"
require "openapi_kit/codegen/emit/decode"
require "openapi_kit/codegen/emit/types"
require "openapi_kit/codegen/emit/codecs"
require "openapi_kit/codegen/emit/forms"
require "openapi_kit/codegen/emit/operations"
require "openapi_kit/codegen/emit/handlers"
require "openapi_kit/codegen/emit/security"
require "openapi_kit/codegen/emit/registry"
require "openapi_kit/codegen/emit/routes"
require "openapi_kit/codegen/emit/controllers"
require "openapi_kit/codegen/generator"
require "openapi_kit/codegen/cli"

module OpenAPIKit
  module Codegen
    MARKER = "# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit"
  end
end
