# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Container
    extend T::Sig

    HANDLERS = T.let(
      {
        "v1.handlers.mods" => Server::Handlers::Mods,
        "v1.handlers.system" => Server::Handlers::System,
      }.freeze,
      T::Hash[::String, T::Module[T.anything]]
    )

    AUTHENTICATORS = T.let(
      {
        "v1.security.bearer_auth" => Server::Security::BearerAuth,
        "v1.security.api_key_auth" => Server::Security::ApiKeyAuth,
      }.freeze,
      T::Hash[::String, T::Module[T.anything]]
    )

    sig { params(container: T.untyped).void }
    def self.verify!(container)
      ::Oapi::Container.verify!(container, HANDLERS.merge(AUTHENTICATORS))
    end
  end
end
