# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  class ModsController < ::Oapi::Rails::Controller
    extend T::Sig

    sig { void }
    def list_mods
      path_params = request.path_parameters.transform_keys(&:to_s)
      query_params = request.query_parameters
      header_params = ::Oapi::Rails.headers(request, ["Application-Name"])

      decoded = Server::Operations::ListMods::Request.new(
        path: Server::Operations::ListMods::Path.new(
          game_domain: ::Oapi::Decode.field(path_params, "gameDomain") { |v| ::Oapi::Codec::Primitive::String::CODEC.from_wire(v) },
        ),
        query: Server::Operations::ListMods::Query.new(
          page: ::Oapi::Decode.defaulted(query_params, "page", 1) { |v| ::Oapi::Codec::Primitive::Integer::CODEC.from_wire(v) },
          status: ::Oapi::Decode.optional(query_params, "status") { |v| Server::Types::ModStatus::CODEC.from_wire(v) },
        ),
        headers: Server::Operations::ListMods::Headers.new(
          application_name: ::Oapi::Decode.optional(header_params, "Application-Name") { |v| ::Oapi::Codec::Primitive::String::CODEC.from_wire(v) },
        ),
        http_request: request
      )

      render_openapi(handler.list_mods(request: decoded))
    end

    sig { void }
    def create_mod
      path_params = request.path_parameters.transform_keys(&:to_s)

      decoded = Server::Operations::CreateMod::Request.new(
        path: Server::Operations::CreateMod::Path.new(
          game_domain: ::Oapi::Decode.field(path_params, "gameDomain") { |v| ::Oapi::Codec::Primitive::String::CODEC.from_wire(v) },
        ),
        body: Server::Types::NewMod::CODEC.from_wire(request.request_parameters),
        http_request: request
      )

      render_openapi(handler.create_mod(request: decoded))
    end

    private

    sig { returns(Server::Handlers::Mods) }
    def handler
      T.cast(::Oapi::Rails.container.resolve("v1.handlers.mods"), Server::Handlers::Mods)
    end
  end
end
