# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  class ModsController < ::ApiBaseController
    extend T::Sig

    sig { void }
    def list_mods
      context = authenticate_list_mods

      path_params = ::Oapi::Decode.gather(["gameDomain"]) { |name| request.path_parameters[name.to_sym] }
      query_params = ::Oapi::Decode.gather(["page", "status"]) { |name| request.query_parameters[name] }
      header_params = ::Oapi::Decode.gather(["Application-Name"]) { |name| request.headers[name] }

      decoded = Server::Operations::ListMods::Request.new(
        path: Server::Operations::ListMods::Path.new(
          game_domain: ::Oapi::Decode.field(path_params, "gameDomain") { |v| ::Oapi::Codec::String.from_wire(v) },
        ),
        query: Server::Operations::ListMods::Query.new(
          page: ::Oapi::Decode.defaulted(query_params, "page", 1) { |v| ::Oapi::Codec::Integer.from_wire(v) },
          status: ::Oapi::Decode.optional(query_params, "status") { |v| Server::Types::ModStatus::Codec.from_wire(v) },
        ),
        headers: Server::Operations::ListMods::Headers.new(
          application_name: ::Oapi::Decode.optional(header_params, "Application-Name") { |v| ::Oapi::Codec::String.from_wire(v) },
        ),
        context: context,
        http_request: request
      )

      response = handler.list_mods(request: decoded)
      body = response.to_wire

      return head(response.status) if body.nil?

      render(json: body, status: response.status, content_type: response.content_type)
    end

    sig { void }
    def create_mod
      context = authenticate_create_mod

      path_params = ::Oapi::Decode.gather(["gameDomain"]) { |name| request.path_parameters[name.to_sym] }

      decoded = Server::Operations::CreateMod::Request.new(
        path: Server::Operations::CreateMod::Path.new(
          game_domain: ::Oapi::Decode.field(path_params, "gameDomain") { |v| ::Oapi::Codec::String.from_wire(v) },
        ),
        body: Server::Types::NewMod::Codec.from_wire(request.request_parameters),
        context: context,
        http_request: request
      )

      response = handler.create_mod(request: decoded)
      body = response.to_wire

      return head(response.status) if body.nil?

      render(json: body, status: response.status, content_type: response.content_type)
    end

    private

    sig { returns(Server::Handlers::Mods) }
    def handler = Server::Container.mods(oapi_container)

    sig { returns(::Demo::Principal) }
    def authenticate_list_mods
      ::Oapi::Security.first_of(
        [
          -> { Server::Container.bearer_auth(oapi_container).authenticate(request: request, scopes: []) },
        ]
      ) || raise(::Oapi::Security::Unauthenticated)
    end

    sig { returns(::Demo::Principal) }
    def authenticate_create_mod
      ::Oapi::Security.first_of(
        [
          -> { Server::Container.bearer_auth(oapi_container).authenticate(request: request, scopes: ["mods:write"]) },
          -> { Server::Container.api_key_auth(oapi_container).authenticate(request: request, scopes: []) },
        ]
      ) || raise(::Oapi::Security::Unauthenticated)
    end
  end
end
