# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module Server
  class Registry < T::Struct
    const :mods, Server::Handlers::Mods
    const :files, Server::Handlers::Files
    const :system, Server::Handlers::System
    const :bearer_auth, Server::Security::BearerAuth
    const :api_key_auth, Server::Security::ApiKeyAuth
  end
end
