# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  class Registry
    extend T::Sig

    sig do
      params(
        mods: T.proc.returns(Server::Handlers::Mods),
        system: T.proc.returns(Server::Handlers::System),
        bearer_auth: T.proc.returns(Server::Security::BearerAuth),
        api_key_auth: T.proc.returns(Server::Security::ApiKeyAuth)
      ).void
    end
    def initialize(mods:, system:, bearer_auth:, api_key_auth:)
      @mods_factory = mods
      @mods = T.let(nil, T.nilable(Server::Handlers::Mods))
      @system_factory = system
      @system = T.let(nil, T.nilable(Server::Handlers::System))
      @bearer_auth_factory = bearer_auth
      @bearer_auth = T.let(nil, T.nilable(Server::Security::BearerAuth))
      @api_key_auth_factory = api_key_auth
      @api_key_auth = T.let(nil, T.nilable(Server::Security::ApiKeyAuth))
    end

    sig { returns(Server::Handlers::Mods) }
    def mods = @mods ||= @mods_factory.call

    sig { returns(Server::Handlers::System) }
    def system = @system ||= @system_factory.call

    sig { returns(Server::Security::BearerAuth) }
    def bearer_auth = @bearer_auth ||= @bearer_auth_factory.call

    sig { returns(Server::Security::ApiKeyAuth) }
    def api_key_auth = @api_key_auth ||= @api_key_auth_factory.call

    sig do
      params(
        mods: T.nilable(Server::Handlers::Mods),
        system: T.nilable(Server::Handlers::System),
        bearer_auth: T.nilable(Server::Security::BearerAuth),
        api_key_auth: T.nilable(Server::Security::ApiKeyAuth)
      ).returns(Registry)
    end
    def swap(mods: nil, system: nil, bearer_auth: nil, api_key_auth: nil)
      Registry.new(
        mods: mods ? -> { mods } : @mods_factory,
        system: system ? -> { system } : @system_factory,
        bearer_auth: bearer_auth ? -> { bearer_auth } : @bearer_auth_factory,
        api_key_auth: api_key_auth ? -> { api_key_auth } : @api_key_auth_factory,
      )
    end

    sig { params(container: T.untyped).returns(Registry) }
    def self.from(container)
      new(
        mods: -> { T.cast(container.resolve("v1.handlers.mods"), Server::Handlers::Mods) },
        system: -> { T.cast(container.resolve("v1.handlers.system"), Server::Handlers::System) },
        bearer_auth: -> { T.cast(container.resolve("v1.security.bearer_auth"), Server::Security::BearerAuth) },
        api_key_auth: -> { T.cast(container.resolve("v1.security.api_key_auth"), Server::Security::ApiKeyAuth) },
      )
    end
  end
end
