# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Routes
    extend T::Sig

    sig { params(mapper: ::ActionDispatch::Routing::Mapper).void }
    def self.draw(mapper)
      mapper.get("/v1/games/:gameDomain/mods", to: "server/mods#list_mods")
      mapper.post("/v1/games/:gameDomain/mods", to: "server/mods#create_mod")
      mapper.get("/v1/health", to: "server/system#get_health")
    end
  end
end
