# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module Server
  module Security
    extend T::Sig

    BEARER_AUTH = T.let(
      ::OpenAPIKit::Security::Http.new(
        name: "bearerAuth",
        scheme: "bearer",
        bearer_format: "JWT"
      ),
      ::OpenAPIKit::Security::Http
    )

    API_KEY_AUTH = T.let(
      ::OpenAPIKit::Security::ApiKey.new(
        name: "apiKeyAuth",
        location: ::OpenAPIKit::Security::ApiKeyLocation::Header,
        parameter_name: "X-Api-Key"
      ),
      ::OpenAPIKit::Security::ApiKey
    )

    SCHEMES = T.let(
      {
        "bearerAuth" => BEARER_AUTH,
        "apiKeyAuth" => API_KEY_AUTH,
      }.freeze,
      T::Hash[::String, ::OpenAPIKit::Security::Scheme]
    )

    module BearerAuth
      extend T::Sig
      extend T::Helpers
      abstract!

      sig { returns(::OpenAPIKit::Security::Http) }
      def scheme = BEARER_AUTH

      sig { params(request: ::ActionDispatch::Request).returns(T.nilable(::String)) }
      def credential(request) = ::OpenAPIKit::Security.credential(scheme, request)

      sig do
        abstract.params(request: ::ActionDispatch::Request, scopes: T::Array[::String])
                .returns(T.nilable(::Demo::Principal))
      end
      def authenticate(request:, scopes:); end
    end

    module ApiKeyAuth
      extend T::Sig
      extend T::Helpers
      abstract!

      sig { returns(::OpenAPIKit::Security::ApiKey) }
      def scheme = API_KEY_AUTH

      sig { params(request: ::ActionDispatch::Request).returns(T.nilable(::String)) }
      def credential(request) = ::OpenAPIKit::Security.credential(scheme, request)

      sig do
        abstract.params(request: ::ActionDispatch::Request, scopes: T::Array[::String])
                .returns(T.nilable(::Demo::Principal))
      end
      def authenticate(request:, scopes:); end
    end
  end
end
