# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  class SystemController < ::ApiBaseController
    extend T::Sig

    sig { void }
    def get_health
      decoded = Server::Operations::GetHealth::Request.new(
        http_request: request
      )

      render_response(handler.get_health(request: decoded))
    end

    private

    sig { returns(Server::Handlers::System) }
    def handler = Server.registry.system

    sig { params(result: ::Oapi::Response).void }
    def render_response(result)
      case (body = result.to_body)
      when ::Oapi::Body::Empty
        head(result.status)
      when ::Oapi::Body::Json
        render(json: body.wire, status: result.status, content_type: result.content_type)
      when ::Oapi::Body::Binary
        response.headers["Content-Type"] = result.content_type.to_s
        response.status = result.status
        self.response_body = body
      else T.absurd(body)
      end
    end
  end
end
