# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  class SystemController < ::Oapi::Rails::Controller
    extend T::Sig

    sig { void }
    def get_health
      decoded = Server::Operations::GetHealth::Request.new(
        http_request: request
      )

      render_openapi(handler.get_health(request: decoded))
    end

    private

    sig { returns(Server::Handlers::System) }
    def handler
      T.cast(::Oapi::Rails.container.resolve("v1.handlers.system"), Server::Handlers::System)
    end
  end
end
