# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  class SystemController < ::ApiBaseController
    extend T::Sig

    sig { void }
    def get_health
      decoded = Server::Operations::GetHealth::Request.new(
        http_request: request
      )

      response = handler.get_health(request: decoded)
      body = response.to_wire

      return head(response.status) if body.nil?

      render(json: body, status: response.status, content_type: response.content_type)
    end

    private

    sig { returns(Server::Handlers::System) }
    def handler = Server::Container.system(oapi_container)
  end
end
