# typed: strict
# frozen_string_literal: true

require "fileutils"
require "pathname"
require "prism"

module OpenAPIKit
  module Codegen
    class Writer
      extend T::Sig

      sig { params(output: Pathname).void }
      def initialize(output:)
        @output = output
      end

      sig { void }
      def clean!
        existing = owned.select(&:file?).sort
        foreign = existing.reject { |path| path.read.start_with?(MARKER) }
        unless foreign.empty?
          raise Error,
                "Refusing to clean #{output}: #{foreign.size} file#{"s" if foreign.size > 1} " \
                "not generated by openapi_kit " \
                "(#{foreign.first(3).map { |f| f.relative_path_from(output.dirname) }.join(", ")}" \
                "#{"…" if foreign.size > 3}). Point `output` at a directory openapi_kit owns."
        end

        existing.each(&:delete)
        prune_empty_directories
      end

      # openapi_kit owns the output directory and the file beside it that names the
      # namespace, because Zeitwerk expects `Api::V3::Generated` in generated.rb rather
      # than inside generated/.
      sig { returns(T::Array[Pathname]) }
      def owned
        (output.directory? ? output.glob("**/*.rb") : []) + [namespace_file]
      end

      sig { returns(Pathname) }
      def namespace_file = output.dirname.join("#{output.basename}.rb")

      sig { params(files: T::Array[Emit::SourceFile]).returns(T::Array[Pathname]) }
      def write_all(files)
        files.each { |file| verify_syntax!(file.path, file.contents) }
        reject_duplicate_paths!(files)

        clean!
        files.map { |file| write(file.path, file.contents, beside_output: file.beside_output) }
      end

      sig { params(name: String, content: String, beside_output: T::Boolean).returns(Pathname) }
      def write(name, content, beside_output: false)
        verify_syntax!(name, content)
        path = beside_output ? output.dirname.join(name) : output.join(name)
        FileUtils.mkdir_p(path.dirname)
        body = content.end_with?("\n") ? content : "#{content}\n"
        path.write("#{MARKER}\n#{body}")
        path
      end

      private

      sig { returns(Pathname) }
      attr_reader :output

      sig { params(files: T::Array[Emit::SourceFile]).void }
      def reject_duplicate_paths!(files)
        duplicates = files.group_by(&:path).select { |_, group| group.size > 1 }
        return if duplicates.empty?

        raise Error,
              "openapi_kit generated more than one file for #{duplicates.keys.sort.join(", ")}. " \
              "Two names in your document normalise to the same constant. " \
              "Disambiguate them, or set name_overrides in your config."
      end

      sig { void }
      def prune_empty_directories
        output.glob("**/*").select(&:directory?).sort.reverse_each do |directory|
          directory.rmdir if directory.children.empty?
        end
      end

      sig { params(name: String, content: String).void }
      def verify_syntax!(name, content)
        result = Prism.parse(content)
        return if result.success?

        error = T.must(result.errors.first)
        line = error.location.start_line
        raise Error,
              "openapi_kit generated invalid Ruby in #{name} at line #{line}: #{error.message}\n  " \
              "#{content.lines[line - 1]&.strip}\n" \
              "This is a bug in openapi_kit, not in your schema. Please report it."
      end
    end
  end
end
