# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module Server
  module Controllers
    class FilesController < ::ApiBaseController
      extend T::Sig
      include ::OpenAPIKit::Rendering

      sig { void }
      def download_mod_file
        path_params = ::OpenAPIKit::Decode.gather(["gameDomain", "modId"]) { |name| request.path_parameters[name.to_sym] }

        decoded = Server::Operations::DownloadModFile::Request.new(
          path: Server::Operations::DownloadModFile::Path.new(
            game_domain: ::OpenAPIKit::Decode.required(path_params, "gameDomain") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
            mod_id: ::OpenAPIKit::Decode.required(path_params, "modId") { |v| ::OpenAPIKit::Codec::Integer.from_wire(v) },
          ),
          http_request: request
        )

        render_response(handler.download_mod_file(request: decoded))
      end

      sig { void }
      def upload_mod_file
        path_params = ::OpenAPIKit::Decode.gather(["gameDomain", "modId"]) { |name| request.path_parameters[name.to_sym] }

        decoded = Server::Operations::UploadModFile::Request.new(
          path: Server::Operations::UploadModFile::Path.new(
            game_domain: ::OpenAPIKit::Decode.required(path_params, "gameDomain") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
            mod_id: ::OpenAPIKit::Decode.required(path_params, "modId") { |v| ::OpenAPIKit::Codec::Integer.from_wire(v) },
          ),
          body: Server::Types::UploadModFileBody::Form.from_parts(request.request_parameters),
          http_request: request
        )

        render_response(handler.upload_mod_file(request: decoded))
      end

      private

      sig { returns(Server::Handlers::Files) }
      def handler = Server::Registry.instance.files
    end
  end
end
