# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Controllers
    class FilesController < ::ApiBaseController
      extend T::Sig

      sig { void }
      def download_mod_file
        path_params = ::Oapi::Decode.gather(["gameDomain", "modId"]) { |name| request.path_parameters[name.to_sym] }

        decoded = Server::Operations::DownloadModFile::Request.new(
          path: Server::Operations::DownloadModFile::Path.new(
            game_domain: ::Oapi::Decode.required(path_params, "gameDomain") { |v| ::Oapi::Codec::String.from_wire(v) },
            mod_id: ::Oapi::Decode.required(path_params, "modId") { |v| ::Oapi::Codec::Integer.from_wire(v) },
          ),
          http_request: request
        )

        render_response(handler.download_mod_file(request: decoded))
      end

      sig { void }
      def upload_mod_file
        path_params = ::Oapi::Decode.gather(["gameDomain", "modId"]) { |name| request.path_parameters[name.to_sym] }

        decoded = Server::Operations::UploadModFile::Request.new(
          path: Server::Operations::UploadModFile::Path.new(
            game_domain: ::Oapi::Decode.required(path_params, "gameDomain") { |v| ::Oapi::Codec::String.from_wire(v) },
            mod_id: ::Oapi::Decode.required(path_params, "modId") { |v| ::Oapi::Codec::Integer.from_wire(v) },
          ),
          body: Server::Types::UploadModFileBody::Form.from_parts(request.request_parameters),
          http_request: request
        )

        render_response(handler.upload_mod_file(request: decoded))
      end

      private

      sig { returns(Server::Handlers::Files) }
      def handler = Server.registry.files

      sig { params(result: ::Oapi::Response).void }
      def render_response(result)
        case (body = result.to_body)
        when ::Oapi::Body::Empty
          head(result.status)
        when ::Oapi::Body::Json
          render(json: body.wire, status: result.status, content_type: result.content_type)
        when ::Oapi::Body::Binary
          response.headers["Content-Type"] = result.content_type.to_s
          response.status = result.status
          self.response_body = body
        else T.absurd(body)
        end
      end
    end
  end
end
