# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Controllers
    class ModsController < ::ApiBaseController
      extend T::Sig
      include ::Oapi::Rendering

      sig { void }
      def list_mods
        principal = authenticate_list_mods

        path_params = ::Oapi::Decode.gather(["gameDomain"]) { |name| request.path_parameters[name.to_sym] }
        query_params = ::Oapi::Decode.gather(["page", "status"]) { |name| request.query_parameters[name] }
        header_params = ::Oapi::Decode.gather(["Application-Name"]) { |name| request.headers[name] }

        decoded = Server::Operations::ListMods::Request.new(
          path: Server::Operations::ListMods::Path.new(
            game_domain: ::Oapi::Decode.required(path_params, "gameDomain") { |v| ::Oapi::Codec::String.from_wire(v) },
          ),
          query: Server::Operations::ListMods::Query.new(
            page: ::Oapi::Decode.defaulted(query_params, "page", 1) { |v| ::Oapi::Codec::Integer.from_wire(v) },
            status: ::Oapi::Decode.optional(query_params, "status") { |v| Server::Types::ModStatus::Codec.from_wire(v) },
          ),
          headers: Server::Operations::ListMods::Headers.new(
            application_name: ::Oapi::Decode.optional(header_params, "Application-Name") { |v| ::Oapi::Codec::String.from_wire(v) },
          ),
          principal: principal,
          http_request: request
        )

        render_response(handler.list_mods(request: decoded))
      end

      sig { void }
      def create_mod
        principal = authenticate_create_mod

        path_params = ::Oapi::Decode.gather(["gameDomain"]) { |name| request.path_parameters[name.to_sym] }

        decoded = Server::Operations::CreateMod::Request.new(
          path: Server::Operations::CreateMod::Path.new(
            game_domain: ::Oapi::Decode.required(path_params, "gameDomain") { |v| ::Oapi::Codec::String.from_wire(v) },
          ),
          body: Server::Types::NewMod::Codec.from_wire(request.request_parameters),
          principal: principal,
          http_request: request
        )

        render_response(handler.create_mod(request: decoded))
      end

      private

      sig { returns(Server::Handlers::Mods) }
      def handler = Server.registry.mods

      sig { returns(::Demo::Principal) }
      def authenticate_list_mods
        ::Oapi::Security.first_of(
          [
            -> { Server.registry.bearer_auth.authenticate(request: request, scopes: []) },
          ]
        ) || raise(::Oapi::Unauthenticated)
      end

      sig { returns(::Demo::Principal) }
      def authenticate_create_mod
        ::Oapi::Security.first_of(
          [
            -> { Server.registry.bearer_auth.authenticate(request: request, scopes: ["mods:write"]) },
            -> { Server.registry.api_key_auth.authenticate(request: request, scopes: []) },
          ]
        ) || raise(::Oapi::Unauthenticated)
      end
    end
  end
end
