# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module Server
  module Controllers
    class ModsController < ::ApiBaseController
      extend T::Sig
      include ::OpenAPIKit::Rendering

      sig { void }
      def list_mods
        principal = authenticate_list_mods

        path_params = ::OpenAPIKit::Decode.gather(["gameDomain"]) { |name| request.path_parameters[name.to_sym] }
        query_params = ::OpenAPIKit::Decode.gather(["page", "status"]) { |name| request.query_parameters[name] }
        header_params = ::OpenAPIKit::Decode.gather(["Application-Name"]) { |name| request.headers[name] }

        decoded = Server::Operations::ListMods::Request.new(
          path: Server::Operations::ListMods::Path.new(
            game_domain: ::OpenAPIKit::Decode.required(path_params, "gameDomain") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
          ),
          query: Server::Operations::ListMods::Query.new(
            page: ::OpenAPIKit::Decode.defaulted(query_params, "page", 1) { |v| ::OpenAPIKit::Codec::Integer.from_wire(v) },
            status: ::OpenAPIKit::Decode.optional(query_params, "status") { |v| Server::Types::ModStatus::Codec.from_wire(v) },
          ),
          headers: Server::Operations::ListMods::Headers.new(
            application_name: ::OpenAPIKit::Decode.optional(header_params, "Application-Name") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
          ),
          principal: principal,
          http_request: request
        )

        render_response(handler.list_mods(request: decoded))
      end

      sig { void }
      def create_mod
        principal = authenticate_create_mod

        path_params = ::OpenAPIKit::Decode.gather(["gameDomain"]) { |name| request.path_parameters[name.to_sym] }

        decoded = Server::Operations::CreateMod::Request.new(
          path: Server::Operations::CreateMod::Path.new(
            game_domain: ::OpenAPIKit::Decode.required(path_params, "gameDomain") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
          ),
          body: Server::Types::NewMod::Codec.from_wire(request.request_parameters),
          principal: principal,
          http_request: request
        )

        render_response(handler.create_mod(request: decoded))
      end

      private

      sig { returns(Server::Handlers::Mods) }
      def handler = Server::Registry.instance.mods

      sig { returns(::Demo::Principal) }
      def authenticate_list_mods
        ::OpenAPIKit::Security.first_of(
          [
            -> { Server::Registry.instance.bearer_auth.authenticate(request: request, scopes: []) },
          ]
        ) || raise(::OpenAPIKit::SecurityError)
      end

      sig { returns(::Demo::Principal) }
      def authenticate_create_mod
        ::OpenAPIKit::Security.first_of(
          [
            -> { Server::Registry.instance.bearer_auth.authenticate(request: request, scopes: ["mods:write"]) },
            -> { Server::Registry.instance.api_key_auth.authenticate(request: request, scopes: []) },
          ]
        ) || raise(::OpenAPIKit::SecurityError)
      end
    end
  end
end
