# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module Server
  module Controllers
    class SystemController < ::ApiBaseController
      extend T::Sig
      include ::OpenAPIKit::Rendering

      sig { void }
      def get_health
        decoded = Server::Operations::GetHealth::Request.new(
          http_request: request
        )

        render_response(handler.get_health(request: decoded))
      end

      private

      sig { returns(Server::Handlers::System) }
      def handler = Server.registry.system
    end
  end
end
