# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Handlers
    module Files
      extend T::Sig
      extend T::Helpers
      interface!

      sig do
        abstract
          .params(request: Server::Operations::DownloadModFile::Request)
          .returns(Server::Operations::DownloadModFile::Response)
      end
      def download_mod_file(request:); end

      sig do
        abstract
          .params(request: Server::Operations::UploadModFile::Request)
          .returns(Server::Operations::UploadModFile::Response)
      end
      def upload_mod_file(request:); end
    end
  end
end
