# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module Server
  module Handlers
    module Mods
      extend T::Sig
      extend T::Helpers
      interface!

      sig do
        abstract
          .params(request: Server::Operations::ListMods::Request)
          .returns(Server::Operations::ListMods::Response)
      end
      def list_mods(request:); end

      sig do
        abstract
          .params(request: Server::Operations::CreateMod::Request)
          .returns(Server::Operations::CreateMod::Response)
      end
      def create_mod(request:); end
    end
  end
end
