# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module Server
  module Handlers
    module System
      extend T::Sig
      extend T::Helpers
      interface!

      sig do
        abstract
          .params(request: Server::Operations::GetHealth::Request)
          .returns(Server::Operations::GetHealth::Response)
      end
      def get_health(request:); end
    end
  end
end
