# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Operations
    module CreateMod
      class Path < T::Struct
        extend T::Sig

        const :game_domain, ::String
      end

      class Request < T::Struct
        extend T::Sig

        const :path, Path
        const :body, Server::Types::NewMod
        const :context, ::Demo::Principal
        const :http_request, ::ActionDispatch::Request
      end

      module Response
        extend T::Helpers
        include ::Oapi::Response
        abstract!
        sealed!
      end

      class Created < T::Struct
        extend T::Sig
        include Response

        const :body, Server::Types::Mod

        sig { override.returns(::Integer) }
        def status = 201

        sig { override.returns(::Oapi::Body) }
        def to_body = ::Oapi::Body::Json.new(wire: Server::Types::Mod::Codec.to_wire(body))

        sig { override.returns(T.nilable(::String)) }
        def content_type = "application/json"
      end

      class NoContent < T::Struct
        extend T::Sig
        include Response

        sig { override.returns(::Integer) }
        def status = 204

        sig { override.returns(::Oapi::Body) }
        def to_body = ::Oapi::Body::Empty.new

        sig { override.returns(T.nilable(::String)) }
        def content_type = nil
      end

      class Default < T::Struct
        extend T::Sig
        include Response

        const :body, Server::Types::ProblemDetails
        const :status_code, ::Integer

        sig { override.returns(::Integer) }
        def status = status_code

        sig { override.returns(::Oapi::Body) }
        def to_body = ::Oapi::Body::Json.new(wire: Server::Types::ProblemDetails::Codec.to_wire(body))

        sig { override.returns(T.nilable(::String)) }
        def content_type = "application/problem+json"
      end
    end
  end
end
