# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module Server
  module Operations
    module DownloadModFile
      class Path < T::Struct
        extend T::Sig

        const :game_domain, ::String
        const :mod_id, ::Integer
      end

      class Request < T::Struct
        extend T::Sig

        const :path, Path
        const :http_request, ::ActionDispatch::Request
      end

      module Response
        extend T::Helpers
        include ::OpenAPIKit::Response
        abstract!
        sealed!
      end

      class Ok < T::Struct
        extend T::Sig
        include Response

        const :body, ::OpenAPIKit::Body::Binary

        sig { override.returns(::Integer) }
        def status = 200

        sig { override.returns(::OpenAPIKit::Body) }
        def to_body = body

        sig { override.returns(T.nilable(::String)) }
        def content_type = "application/octet-stream"
      end

      class NotFound < T::Struct
        extend T::Sig
        include Response

        const :body, Server::Types::ProblemDetails

        sig { override.returns(::Integer) }
        def status = 404

        sig { override.returns(::OpenAPIKit::Body) }
        def to_body = ::OpenAPIKit::Body::Json.new(wire: Server::Types::ProblemDetails::Codec.to_wire(body))

        sig { override.returns(T.nilable(::String)) }
        def content_type = "application/problem+json"
      end
    end
  end
end
