# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Operations
    module GetHealth
      class Request < T::Struct
        extend T::Sig

        const :http_request, ::ActionDispatch::Request
      end

      module Response
        extend T::Sig
        extend T::Helpers
        abstract!
        sealed!

        sig { abstract.returns(::Integer) }
        def status; end

        sig { abstract.returns(::Oapi::Wire::Out) }
        def to_wire; end

        sig { abstract.returns(T.nilable(::String)) }
        def content_type; end
      end

      class Ok < T::Struct
        extend T::Sig
        include Response

        sig { override.returns(::Integer) }
        def status = 200

        sig { override.returns(::Oapi::Wire::Out) }
        def to_wire = nil

        sig { override.returns(T.nilable(::String)) }
        def content_type = nil
      end
    end
  end
end
