# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Operations
    module GetHealth
      class Request < T::Struct
        extend T::Sig

        const :http_request, ::ActionDispatch::Request
      end

      module Response
        extend T::Helpers
        include ::Oapi::Response
        abstract!
        sealed!
      end

      class Ok < T::Struct
        extend T::Sig
        include Response

        sig { override.returns(::Integer) }
        def status = 200

        sig { override.returns(::Oapi::Body) }
        def to_body = ::Oapi::Body::Empty.new

        sig { override.returns(T.nilable(::String)) }
        def content_type = nil
      end
    end
  end
end
