# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Operations
    module ListMods
      extend T::Sig

      SECURITY = T.let(
        [
          ::Oapi::Security::Requirement.new(schemes: {"bearerAuth" => []}),
        ].freeze,
        T::Array[::Oapi::Security::Requirement]
      )

      sig do
        params(request: ::ActionDispatch::Request, container: T.untyped)
          .returns(::Demo::User)
      end
      def self.authenticate(request:, container:)
        authenticator = T.cast(container.resolve("v1.security.bearer_auth"), Server::Security::BearerAuth)
        principal = authenticator.authenticate(request: request, scopes: [])
        return principal unless principal.nil?

        raise ::Oapi::Security::Unauthenticated
      end

      class Path < T::Struct
        extend T::Sig

        const :game_domain, ::String
      end

      class Query < T::Struct
        extend T::Sig

        const :page, ::Integer, default: 1
        const :status, T.nilable(Server::Types::ModStatus)
      end

      class Headers < T::Struct
        extend T::Sig

        const :application_name, T.nilable(::String)
      end

      class Request < T::Struct
        extend T::Sig

        const :path, Path
        const :query, Query
        const :headers, Headers
        const :context, ::Demo::User
        const :http_request, ::ActionDispatch::Request
      end

      module Response
        extend T::Sig
        extend T::Helpers
        abstract!
        sealed!

        sig { abstract.returns(::Integer) }
        def status; end

        sig { abstract.returns(::Oapi::Wire) }
        def to_wire; end

        sig { abstract.returns(T.nilable(::String)) }
        def content_type; end
      end

      class Ok < T::Struct
        extend T::Sig
        include Response

        const :body, T::Array[Server::Types::Mod]

        sig { override.returns(::Integer) }
        def status = 200

        sig { override.returns(::Oapi::Wire) }
        def to_wire = body.map { |item| Server::Types::Mod::Codec.to_wire(item) }

        sig { override.returns(T.nilable(::String)) }
        def content_type = "application/json"
      end

      class BadRequest < T::Struct
        extend T::Sig
        include Response

        const :body, Server::Types::ProblemDetails

        sig { override.returns(::Integer) }
        def status = 400

        sig { override.returns(::Oapi::Wire) }
        def to_wire = Server::Types::ProblemDetails::Codec.to_wire(body)

        sig { override.returns(T.nilable(::String)) }
        def content_type = "application/problem+json"
      end
    end
  end
end
