# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Operations
    module ListMods
      class Path < T::Struct
        extend T::Sig

        const :game_domain, ::String
      end

      class Query < T::Struct
        extend T::Sig

        const :page, ::Integer, default: 1
        const :status, T.nilable(Server::Types::ModStatus)
      end

      class Headers < T::Struct
        extend T::Sig

        const :application_name, T.nilable(::String)
      end

      class Request < T::Struct
        extend T::Sig

        const :path, Path
        const :query, Query
        const :headers, Headers
        const :context, ::Demo::Principal
        const :http_request, ::ActionDispatch::Request
      end

      module Response
        extend T::Helpers
        include ::Oapi::Response
        abstract!
        sealed!
      end

      class Ok < T::Struct
        extend T::Sig
        include Response

        const :body, T::Array[Server::Types::Mod]

        sig { override.returns(::Integer) }
        def status = 200

        sig { override.returns(::Oapi::Body) }
        def to_body = ::Oapi::Body::Json.new(wire: body.map { |item| Server::Types::Mod::Codec.to_wire(item) })

        sig { override.returns(T.nilable(::String)) }
        def content_type = "application/json"
      end

      class BadRequest < T::Struct
        extend T::Sig
        include Response

        const :body, Server::Types::ProblemDetails

        sig { override.returns(::Integer) }
        def status = 400

        sig { override.returns(::Oapi::Body) }
        def to_body = ::Oapi::Body::Json.new(wire: Server::Types::ProblemDetails::Codec.to_wire(body))

        sig { override.returns(T.nilable(::String)) }
        def content_type = "application/problem+json"
      end
    end
  end
end
