# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module Server
  module Operations
    module UploadModFile
      class Path < T::Struct
        extend T::Sig

        const :game_domain, ::String
        const :mod_id, ::Integer
      end

      class Request < T::Struct
        extend T::Sig

        const :path, Path
        const :body, Server::Types::UploadModFileBody
        const :http_request, ::ActionDispatch::Request
      end

      module Response
        extend T::Helpers
        include ::OpenAPIKit::Response
        abstract!
        sealed!
      end

      class NoContent < T::Struct
        extend T::Sig
        include Response

        sig { override.returns(::Integer) }
        def status = 204

        sig { override.returns(::OpenAPIKit::Body) }
        def to_body = ::OpenAPIKit::Body::Empty.new

        sig { override.returns(T.nilable(::String)) }
        def content_type = nil
      end
    end
  end
end
