# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Operations
    module UploadModFile
      class Path < T::Struct
        extend T::Sig

        const :game_domain, ::String
        const :mod_id, ::Integer
      end

      class Request < T::Struct
        extend T::Sig

        const :path, Path
        const :body, Server::Types::UploadModFileBody
        const :http_request, ::ActionDispatch::Request
      end

      module Response
        extend T::Helpers
        include ::Oapi::Response
        abstract!
        sealed!
      end

      class NoContent < T::Struct
        extend T::Sig
        include Response

        sig { override.returns(::Integer) }
        def status = 204

        sig { override.returns(::Oapi::Body) }
        def to_body = ::Oapi::Body::Empty.new

        sig { override.returns(T.nilable(::String)) }
        def content_type = nil
      end
    end
  end
end
