# typed: strict
# frozen_string_literal: true

require "sorbet-runtime"

require "oapi/runtime"

require "oapi/version"
require "oapi/errors"
require "oapi/ruby_type"
require "oapi/naming"
require "oapi/ir/schema"
require "oapi/ir/type_def"
require "oapi/ir/document"
require "oapi/config"
require "oapi/writer"
require "oapi/loader"
require "oapi/types/builtins"
require "oapi/types/registry"
require "oapi/emit/buffer"
require "oapi/emit/types"
require "oapi/generator"
require "oapi/cli"

module Oapi
  MARKER = "# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi"
end
