# typed: strict
# frozen_string_literal: true

require "sorbet-runtime"

require "oapi/runtime"

require "oapi/version"
require "oapi/config_error"
require "oapi/schema_error"
require "oapi/ruby_type"
require "oapi/naming"
require "oapi/ir/schema"
require "oapi/ir/type_def"
require "oapi/ir/document"
require "oapi/config"
require "oapi/writer"
require "oapi/loader"
require "oapi/type_registry/defaults"
require "oapi/type_registry"
require "oapi/emit/buffer"
require "oapi/emit/literal"
require "oapi/emit/types"
require "oapi/emit/operations"
require "oapi/emit/handlers"
require "oapi/emit/container"
require "oapi/generator"
require "oapi/cli"

module Oapi
  MARKER = "# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi"
end
