# frozen_string_literal: true

# The trees the suite compares generated output against. Regenerated by `rake golden`,
# and compared, not rebuilt, by the specs, so a change to an emitter shows up as a diff.
module Golden
  ROOT = Pathname.new(__dir__).join("../golden")

  FIXTURES = {
    "kitchen_sink" => { "modules" => %w[KitchenSink] },
    "server" => {
      "modules" => %w[Server],
      "container_prefix" => "v1",
      "principals" => { "bearerAuth" => "::Demo::User", "apiKeyAuth" => "::Demo::Service" }
    }
  }.freeze

  def self.call
    FIXTURES.map do |name, options|
      config = Oapi::Codegen::Config.from_hash(
        {
          "spec" => ROOT.join("../fixtures/schemas/#{name}.yaml").to_s,
          "output" => ROOT.join(name).to_s,
          "controller_base" => "ApiBaseController"
        }.merge(options),
        base: ROOT
      )

      Oapi::Codegen::Generator.new(config: config).generate
    end.flatten
  end
end
