# frozen_string_literal: true

# The trees the suite compares generated output against. Regenerated by `rake golden`,
# and compared, not rebuilt, by the specs, so a change to an emitter shows up as a diff.
module Golden
  ROOT = Pathname.new(__dir__).join("../golden")

  FIXTURES = {
    "kitchen_sink" => { modules: %w[KitchenSink] },
    "server" => {
      modules: %w[Server],
      principal: "::Demo::Principal"
    }
  }.freeze

  def self.call
    FIXTURES.map do |name, options|
      config = Oapi::Codegen::Config.new(
        spec: ROOT.join("../fixtures/schemas/#{name}.yaml").expand_path,
        output: ROOT.join(name).expand_path,
        controller_base: "ApiBaseController",
        **options
      )

      Oapi::Codegen::Generator.new(config: config).generate
    end.flatten
  end
end
