# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class Adversarial < T::Struct
      extend T::Sig

      const :serialize_, ::String
      const :since, ::Time, factory: -> { ::OpenAPIKit::Codec::DateTime.from_wire("2020-01-01T00:00:00Z") }
      const :cleared, T.nilable(::String), default: nil
      const :rate, ::Float, factory: -> { ::OpenAPIKit::Codec::Float.from_wire(1) }
      const :additional_properties, T::Hash[::String, ::Time], factory: -> { {} }

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(Adversarial) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::OpenAPIKit::Codec::Contract

        Value = type_template { { fixed: KitchenSink::Types::Adversarial } }

        sig { override.params(value: ::OpenAPIKit::Wire).returns(KitchenSink::Types::Adversarial) }
        def self.from_wire(value)
          raw = ::OpenAPIKit::Decode.object(value)
          KitchenSink::Types::Adversarial.new(
            serialize_: ::OpenAPIKit::Decode.required(raw, "serialize") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
            since: ::OpenAPIKit::Decode.defaulted(raw, "since", ::OpenAPIKit::Codec::DateTime.from_wire("2020-01-01T00:00:00Z")) { |v| ::OpenAPIKit::Codec::DateTime.from_wire(v) },
            cleared: ::OpenAPIKit::Decode.defaulted(raw, "cleared", nil) { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
            rate: ::OpenAPIKit::Decode.defaulted(raw, "rate", ::OpenAPIKit::Codec::Float.from_wire(1)) { |v| ::OpenAPIKit::Codec::Float.from_wire(v) },
            additional_properties: ::OpenAPIKit::Decode.values(raw.except("serialize", "since", "cleared", "rate")) { |item| ::OpenAPIKit::Codec::DateTime.from_wire(item) },
          )
        end

        sig { override.params(value: KitchenSink::Types::Adversarial).returns(::OpenAPIKit::Wire) }
        def self.to_wire(value)
          wire = T.let({}, T::Hash[::String, ::OpenAPIKit::Wire])
          wire["serialize"] = ::OpenAPIKit::Codec::String.to_wire(value.serialize_)
          since = value.since
          wire["since"] = ::OpenAPIKit::Codec::DateTime.to_wire(since) unless since.nil?
          cleared = value.cleared
          wire["cleared"] = ::OpenAPIKit::Codec::String.to_wire(cleared) unless cleared.nil?
          rate = value.rate
          wire["rate"] = ::OpenAPIKit::Codec::Float.to_wire(rate) unless rate.nil?
          wire.merge!(value.additional_properties.transform_values { |item| ::OpenAPIKit::Codec::DateTime.to_wire(item) })
          wire
        end
      end
    end
  end
end
