# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class Cat < T::Struct
      extend T::Sig

      const :kind, ::String
      const :lives, T.nilable(::Integer)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(Cat) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash
    end
  end
end
