# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class Cat < T::Struct
      extend T::Sig

      const :kind, ::String
      const :lives, T.nilable(::Integer)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(Cat) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::Oapi::Codec::Contract

        Value = type_template { { fixed: KitchenSink::Types::Cat } }

        sig { override.params(value: T.untyped).returns(KitchenSink::Types::Cat) }
        def self.from_wire(value)
          raw = ::Oapi::Decode.object(value)
          KitchenSink::Types::Cat.new(
            kind: ::Oapi::Decode.field(raw, "kind") { |v| ::Oapi::Codec::String.from_wire(v) },
            lives: ::Oapi::Decode.optional(raw, "lives") { |v| ::Oapi::Codec::Integer.from_wire(v) },
          )
        end

        sig { override.params(value: KitchenSink::Types::Cat).returns(::Oapi::Wire) }
        def self.to_wire(value)
          wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
          wire["kind"] = ::Oapi::Codec::String.to_wire(value.kind)
          lives = value.lives
          wire["lives"] = ::Oapi::Codec::Integer.to_wire(lives) unless lives.nil?
          wire
        end
      end
    end
  end
end
