# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class Dog < T::Struct
      extend T::Sig

      const :kind, ::String
      const :breed, T.nilable(::String)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(Dog) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::OpenAPIKit::Codec::Contract

        Value = type_template { { fixed: KitchenSink::Types::Dog } }

        sig { override.params(value: ::OpenAPIKit::Wire).returns(KitchenSink::Types::Dog) }
        def self.from_wire(value)
          raw = ::OpenAPIKit::Decode.object(value)
          KitchenSink::Types::Dog.new(
            kind: ::OpenAPIKit::Decode.required(raw, "kind") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
            breed: ::OpenAPIKit::Decode.optional(raw, "breed") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
          )
        end

        sig { override.params(value: KitchenSink::Types::Dog).returns(::OpenAPIKit::Wire) }
        def self.to_wire(value)
          wire = T.let({}, T::Hash[::String, ::OpenAPIKit::Wire])
          wire["kind"] = ::OpenAPIKit::Codec::String.to_wire(value.kind)
          breed = value.breed
          wire["breed"] = ::OpenAPIKit::Codec::String.to_wire(breed) unless breed.nil?
          wire
        end
      end
    end
  end
end
