# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    module Loose
      Value = T.type_alias { T.any(::String, ::Integer) }

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::OpenAPIKit::Codec::Contract

        Value = type_template { { fixed: KitchenSink::Types::Loose::Value } }

        sig { override.params(value: ::OpenAPIKit::Wire).returns(KitchenSink::Types::Loose::Value) }
        def self.from_wire(value)
          ::OpenAPIKit::Decode.first_of(value, "Loose", [
            ->(candidate) { ::OpenAPIKit::Codec::String.from_wire(candidate) },
            ->(candidate) { ::OpenAPIKit::Codec::Integer.from_wire(candidate) },
          ])
        end

        sig { override.params(value: KitchenSink::Types::Loose::Value).returns(::OpenAPIKit::Wire) }
        def self.to_wire(value)
          case value
          when ::String then ::OpenAPIKit::Codec::String.to_wire(value)
          when ::Integer then ::OpenAPIKit::Codec::Integer.to_wire(value)
          else T.absurd(value)
          end
        end
      end
    end
  end
end
