# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    Loose = T.type_alias { T.any(::String, ::Integer) }
  end
end
