# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class Mod < T::Struct
      extend T::Sig

      const :id, ::Integer
      const :name, ::String
      const :status, T.nilable(KitchenSink::Types::ModStatus)
      const :updated_at, ::Time
      const :deleted_at, T.nilable(::Time)
      const :summary, T.nilable(::String)
      const :bio, ::Oapi::Optional[T.nilable(::String)], factory: -> { ::Oapi::Absent.new }
      const :page_size, ::Integer, default: 20
      const :owner, ::Oapi::Optional[T.nilable(KitchenSink::Types::User)], factory: -> { ::Oapi::Absent.new }
      const :tags, T.nilable(T::Array[::String])
      const :meta, T.nilable(KitchenSink::Types::ModMeta)
      const :extra, T.nilable(T::Hash[::String, ::Integer])

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(Mod) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash
    end
  end
end
