# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class Mod < T::Struct
      extend T::Sig

      const :id, ::Integer
      const :name, ::String
      const :status, T.nilable(KitchenSink::Types::ModStatus)
      const :updated_at, ::Time
      const :deleted_at, T.nilable(::Time)
      const :summary, T.nilable(::String)
      const :bio, ::OpenAPIKit::Optional[T.nilable(::String)], default: ::OpenAPIKit::ABSENT
      const :page_size, ::Integer, default: 20
      const :owner, ::OpenAPIKit::Optional[T.nilable(KitchenSink::Types::User)], default: ::OpenAPIKit::ABSENT
      const :tags, T.nilable(T::Array[::String])
      const :meta, T.nilable(KitchenSink::Types::ModMeta)
      const :extra, T.nilable(T::Hash[::String, ::Integer])

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(Mod) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::OpenAPIKit::Codec::Contract

        Value = type_template { { fixed: KitchenSink::Types::Mod } }

        sig { override.params(value: ::OpenAPIKit::Wire).returns(KitchenSink::Types::Mod) }
        def self.from_wire(value)
          raw = ::OpenAPIKit::Decode.object(value)
          KitchenSink::Types::Mod.new(
            id: ::OpenAPIKit::Decode.required(raw, "id") { |v| ::OpenAPIKit::Codec::Integer.from_wire(v) },
            name: ::OpenAPIKit::Decode.required(raw, "name") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
            status: ::OpenAPIKit::Decode.optional(raw, "status") { |v| KitchenSink::Types::ModStatus::Codec.from_wire(v) },
            updated_at: ::OpenAPIKit::Decode.required(raw, "updatedAt") { |v| ::OpenAPIKit::Codec::DateTime.from_wire(v) },
            deleted_at: ::OpenAPIKit::Decode.required_nullable(raw, "deletedAt") { |v| ::OpenAPIKit::Codec::DateTime.from_wire(v) },
            summary: ::OpenAPIKit::Decode.optional(raw, "summary") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
            bio: ::OpenAPIKit::Decode.optional_nullable(raw, "bio") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
            page_size: ::OpenAPIKit::Decode.defaulted(raw, "pageSize", 20) { |v| ::OpenAPIKit::Codec::Integer.from_wire(v) },
            owner: ::OpenAPIKit::Decode.optional_nullable(raw, "owner") { |v| KitchenSink::Types::User::Codec.from_wire(v) },
            tags: ::OpenAPIKit::Decode.optional(raw, "tags") { |v| OpenAPIKit::Decode.each(v) { |item| ::OpenAPIKit::Codec::String.from_wire(item) } },
            meta: ::OpenAPIKit::Decode.optional(raw, "meta") { |v| KitchenSink::Types::ModMeta::Codec.from_wire(v) },
            extra: ::OpenAPIKit::Decode.optional(raw, "extra") { |v| OpenAPIKit::Decode.values(v) { |item| ::OpenAPIKit::Codec::Integer.from_wire(item) } },
          )
        end

        sig { override.params(value: KitchenSink::Types::Mod).returns(::OpenAPIKit::Wire) }
        def self.to_wire(value)
          wire = T.let({}, T::Hash[::String, ::OpenAPIKit::Wire])
          wire["id"] = ::OpenAPIKit::Codec::Integer.to_wire(value.id)
          wire["name"] = ::OpenAPIKit::Codec::String.to_wire(value.name)
          field = value.status
          wire["status"] = KitchenSink::Types::ModStatus::Codec.to_wire(field) unless field.nil?
          wire["updatedAt"] = ::OpenAPIKit::Codec::DateTime.to_wire(value.updated_at)
          field = value.deleted_at
          wire["deletedAt"] = field.nil? ? nil : ::OpenAPIKit::Codec::DateTime.to_wire(field)
          field = value.summary
          wire["summary"] = ::OpenAPIKit::Codec::String.to_wire(field) unless field.nil?
          field = value.bio
          if field.is_a?(::OpenAPIKit::Present)
            inner = field.value
            wire["bio"] = inner.nil? ? nil : ::OpenAPIKit::Codec::String.to_wire(inner)
          end
          field = value.page_size
          wire["pageSize"] = ::OpenAPIKit::Codec::Integer.to_wire(field) unless field.nil?
          field = value.owner
          if field.is_a?(::OpenAPIKit::Present)
            inner = field.value
            wire["owner"] = inner.nil? ? nil : KitchenSink::Types::User::Codec.to_wire(inner)
          end
          field = value.tags
          wire["tags"] = field.map { |item| ::OpenAPIKit::Codec::String.to_wire(item) } unless field.nil?
          field = value.meta
          wire["meta"] = KitchenSink::Types::ModMeta::Codec.to_wire(field) unless field.nil?
          field = value.extra
          wire["extra"] = field.transform_values { |item| ::OpenAPIKit::Codec::Integer.to_wire(item) } unless field.nil?
          wire
        end
      end
    end
  end
end
