# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class Mod < T::Struct
      extend T::Sig

      const :id, ::Integer
      const :name, ::String
      const :status, T.nilable(KitchenSink::Types::ModStatus)
      const :updated_at, ::Time
      const :deleted_at, T.nilable(::Time)
      const :summary, T.nilable(::String)
      const :bio, ::Oapi::Optional[T.nilable(::String)], factory: -> { ::Oapi::Absent.new }
      const :page_size, ::Integer, default: 20
      const :owner, ::Oapi::Optional[T.nilable(KitchenSink::Types::User)], factory: -> { ::Oapi::Absent.new }
      const :tags, T.nilable(T::Array[::String])
      const :meta, T.nilable(KitchenSink::Types::ModMeta)
      const :extra, T.nilable(T::Hash[::String, ::Integer])

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(Mod) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      class Codec
        extend T::Sig
        extend T::Generic
        include ::Oapi::Codec::Contract

        Value = type_member { { fixed: KitchenSink::Types::Mod } }

        sig { override.params(value: T.untyped).returns(KitchenSink::Types::Mod) }
        def from_wire(value)
          raw = ::Oapi::Decode.object(value)
          KitchenSink::Types::Mod.new(
            id: ::Oapi::Decode.field(raw, "id") { |v| ::Oapi::Codec::Integer::CODEC.from_wire(v) },
            name: ::Oapi::Decode.field(raw, "name") { |v| ::Oapi::Codec::String::CODEC.from_wire(v) },
            status: ::Oapi::Decode.optional(raw, "status") { |v| KitchenSink::Types::ModStatus::CODEC.from_wire(v) },
            updated_at: ::Oapi::Decode.field(raw, "updatedAt") { |v| ::Oapi::Codec::DateTime::CODEC.from_wire(v) },
            deleted_at: ::Oapi::Decode.nullable_field(raw, "deletedAt") { |v| ::Oapi::Codec::DateTime::CODEC.from_wire(v) },
            summary: ::Oapi::Decode.optional(raw, "summary") { |v| ::Oapi::Codec::String::CODEC.from_wire(v) },
            bio: ::Oapi::Decode.tristate(raw, "bio") { |v| ::Oapi::Codec::String::CODEC.from_wire(v) },
            page_size: ::Oapi::Decode.defaulted(raw, "pageSize", 20) { |v| ::Oapi::Codec::Integer::CODEC.from_wire(v) },
            owner: ::Oapi::Decode.tristate(raw, "owner") { |v| KitchenSink::Types::User::CODEC.from_wire(v) },
            tags: ::Oapi::Decode.optional(raw, "tags") { |v| Oapi::Decode.each(v) { |item| ::Oapi::Codec::String::CODEC.from_wire(item) } },
            meta: ::Oapi::Decode.optional(raw, "meta") { |v| KitchenSink::Types::ModMeta::CODEC.from_wire(v) },
            extra: ::Oapi::Decode.optional(raw, "extra") { |v| Oapi::Decode.values(v) { |item| ::Oapi::Codec::Integer::CODEC.from_wire(item) } },
          )
        end

        sig { override.params(value: KitchenSink::Types::Mod).returns(::Oapi::Wire) }
        def to_wire(value)
          wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
          wire["id"] = ::Oapi::Codec::Integer::CODEC.to_wire(value.id)
          wire["name"] = ::Oapi::Codec::String::CODEC.to_wire(value.name)
          status = value.status
          wire["status"] = KitchenSink::Types::ModStatus::CODEC.to_wire(status) unless status.nil?
          wire["updatedAt"] = ::Oapi::Codec::DateTime::CODEC.to_wire(value.updated_at)
          deleted_at = value.deleted_at
          wire["deletedAt"] = deleted_at.nil? ? nil : ::Oapi::Codec::DateTime::CODEC.to_wire(deleted_at)
          summary = value.summary
          wire["summary"] = ::Oapi::Codec::String::CODEC.to_wire(summary) unless summary.nil?
          bio = value.bio
          if bio.is_a?(::Oapi::Present)
            inner = bio.value
            wire["bio"] = inner.nil? ? nil : ::Oapi::Codec::String::CODEC.to_wire(inner)
          end
          page_size = value.page_size
          wire["pageSize"] = ::Oapi::Codec::Integer::CODEC.to_wire(page_size) unless page_size.nil?
          owner = value.owner
          if owner.is_a?(::Oapi::Present)
            inner = owner.value
            wire["owner"] = inner.nil? ? nil : KitchenSink::Types::User::CODEC.to_wire(inner)
          end
          tags = value.tags
          wire["tags"] = tags.map { |item| ::Oapi::Codec::String::CODEC.to_wire(item) } unless tags.nil?
          meta = value.meta
          wire["meta"] = KitchenSink::Types::ModMeta::CODEC.to_wire(meta) unless meta.nil?
          extra = value.extra
          wire["extra"] = extra.transform_values { |item| ::Oapi::Codec::Integer::CODEC.to_wire(item) } unless extra.nil?
          wire
        end
      end

      CODEC = T.let(Codec.new, Codec)
    end
  end
end
