# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class ModMeta < T::Struct
      extend T::Sig

      const :note, T.nilable(::String)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(ModMeta) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::Oapi::Codec::Contract

        Value = type_template { { fixed: KitchenSink::Types::ModMeta } }

        sig { override.params(value: T.untyped).returns(KitchenSink::Types::ModMeta) }
        def self.from_wire(value)
          raw = ::Oapi::Decode.object(value)
          KitchenSink::Types::ModMeta.new(
            note: ::Oapi::Decode.optional(raw, "note") { |v| ::Oapi::Codec::String.from_wire(v) },
          )
        end

        sig { override.params(value: KitchenSink::Types::ModMeta).returns(::Oapi::Wire) }
        def self.to_wire(value)
          wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
          note = value.note
          wire["note"] = ::Oapi::Codec::String.to_wire(note) unless note.nil?
          wire
        end
      end
    end
  end
end
