# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class ModMeta < T::Struct
      extend T::Sig

      const :note, T.nilable(::String)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(ModMeta) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::OpenAPIKit::Codec::Contract

        Value = type_template { { fixed: KitchenSink::Types::ModMeta } }

        sig { override.params(value: ::OpenAPIKit::Wire).returns(KitchenSink::Types::ModMeta) }
        def self.from_wire(value)
          raw = ::OpenAPIKit::Decode.object(value)
          KitchenSink::Types::ModMeta.new(
            note: ::OpenAPIKit::Decode.optional(raw, "note") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
          )
        end

        sig { override.params(value: KitchenSink::Types::ModMeta).returns(::OpenAPIKit::Wire) }
        def self.to_wire(value)
          wire = T.let({}, T::Hash[::String, ::OpenAPIKit::Wire])
          field = value.note
          wire["note"] = ::OpenAPIKit::Codec::String.to_wire(field) unless field.nil?
          wire
        end
      end
    end
  end
end
