# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class ModStatus < T::Enum
      enums do
        Live = new("live")
        UnderModeration = new("under-moderation")
        Hidden = new("hidden")
      end

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::Oapi::Codec::Contract

        Value = type_template { { fixed: KitchenSink::Types::ModStatus } }

        VALUES = T.let(["live", "under-moderation", "hidden"].freeze, T::Array[::Oapi::Wire::Out])

        sig { override.params(value: ::Oapi::Wire::In).returns(KitchenSink::Types::ModStatus) }
        def self.from_wire(value)
          KitchenSink::Types::ModStatus.try_deserialize(value) ||
            raise(::Oapi::DecodeError.new("expected one of #{VALUES.join(", ")}, got #{value.inspect}"))
        end

        sig { override.params(value: KitchenSink::Types::ModStatus).returns(::Oapi::Wire::Out) }
        def self.to_wire(value) = value.serialize
      end
    end
  end
end
