# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    Pet = T.type_alias { T.any(KitchenSink::Types::Cat, KitchenSink::Types::Dog) }
  end
end
