# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    module Pet
      Value = T.type_alias { T.any(KitchenSink::Types::Cat, KitchenSink::Types::Dog) }

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::OpenAPIKit::Codec::Contract

        Value = type_template { { fixed: KitchenSink::Types::Pet::Value } }

        TAGS = T.let(["cat", "dog"].freeze, T::Array[::String])

        sig { override.params(value: ::OpenAPIKit::Wire).returns(KitchenSink::Types::Pet::Value) }
        def self.from_wire(value)
          raw = ::OpenAPIKit::Decode.object(value)
          tag = raw["kind"]
          case tag
          when "cat" then KitchenSink::Types::Cat::Codec.from_wire(raw)
          when "dog" then KitchenSink::Types::Dog::Codec.from_wire(raw)
          else raise(::OpenAPIKit::DecodeError.new("expected kind to be one of #{TAGS.join(", ")}, got #{tag.inspect}"))
          end
        end

        sig { override.params(value: KitchenSink::Types::Pet::Value).returns(::OpenAPIKit::Wire) }
        def self.to_wire(value)
          case value
          when KitchenSink::Types::Cat then KitchenSink::Types::Cat::Codec.to_wire(value)
          when KitchenSink::Types::Dog then KitchenSink::Types::Dog::Codec.to_wire(value)
          else T.absurd(value)
          end
        end
      end
    end
  end
end
