# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    SnakePet = T.type_alias { T.any(KitchenSink::Types::SnakeCat, KitchenSink::Types::SnakeDog) }
  end
end
