# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class SnakeCat < T::Struct
      extend T::Sig

      const :kind, ::String

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(SnakeCat) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::OpenAPIKit::Codec::Contract

        Value = type_template { { fixed: KitchenSink::Types::SnakeCat } }

        sig { override.params(value: ::OpenAPIKit::Wire).returns(KitchenSink::Types::SnakeCat) }
        def self.from_wire(value)
          raw = ::OpenAPIKit::Decode.object(value)
          KitchenSink::Types::SnakeCat.new(
            kind: ::OpenAPIKit::Decode.required(raw, "kind") { |v| ::OpenAPIKit::Codec::String.from_wire(v) },
          )
        end

        sig { override.params(value: KitchenSink::Types::SnakeCat).returns(::OpenAPIKit::Wire) }
        def self.to_wire(value)
          wire = T.let({}, T::Hash[::String, ::OpenAPIKit::Wire])
          wire["kind"] = ::OpenAPIKit::Codec::String.to_wire(value.kind)
          wire
        end
      end
    end
  end
end
