# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    module SnakePet
      Value = T.type_alias { T.any(KitchenSink::Types::SnakeCat, KitchenSink::Types::SnakeDog) }

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::Oapi::Codec::Contract

        Value = type_template { { fixed: KitchenSink::Types::SnakePet::Value } }

        TAGS = T.let(["snake_cat", "snake_dog"].freeze, T::Array[::String])

        sig { override.params(value: T.untyped).returns(KitchenSink::Types::SnakePet::Value) }
        def self.from_wire(value)
          raw = ::Oapi::Decode.object(value)
          tag = raw["kind"]
          case tag
          when "snake_cat" then KitchenSink::Types::SnakeCat::Codec.from_wire(raw)
          when "snake_dog" then KitchenSink::Types::SnakeDog::Codec.from_wire(raw)
          else raise(::Oapi::DecodeError.new("expected kind to be one of #{TAGS.join(", ")}, got #{tag.inspect}"))
          end
        end

        sig { override.params(value: KitchenSink::Types::SnakePet::Value).returns(::Oapi::Wire) }
        def self.to_wire(value)
          case value
          when KitchenSink::Types::SnakeCat then KitchenSink::Types::SnakeCat::Codec.to_wire(value)
          when KitchenSink::Types::SnakeDog then KitchenSink::Types::SnakeDog::Codec.to_wire(value)
          else T.absurd(value)
          end
        end
      end
    end
  end
end
