# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class SnakeDog < T::Struct
      extend T::Sig

      const :kind, ::String

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(SnakeDog) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      class Codec
        extend T::Sig
        extend T::Generic
        include ::Oapi::Codec::Contract

        Value = type_member { { fixed: KitchenSink::Types::SnakeDog } }

        sig { override.params(value: T.untyped).returns(KitchenSink::Types::SnakeDog) }
        def from_wire(value)
          raw = ::Oapi::Decode.object(value)
          KitchenSink::Types::SnakeDog.new(
            kind: ::Oapi::Decode.field(raw, "kind") { |v| ::Oapi::Codec::String::CODEC.from_wire(v) },
          )
        end

        sig { override.params(value: KitchenSink::Types::SnakeDog).returns(::Oapi::Wire) }
        def to_wire(value)
          wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
          wire["kind"] = ::Oapi::Codec::String::CODEC.to_wire(value.kind)
          wire
        end
      end

      CODEC = T.let(Codec.new, Codec)
    end
  end
end
