# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class User < T::Struct
      extend T::Sig

      const :id, ::String
      const :name, ::String
      const :friend, T.nilable(KitchenSink::Types::User)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(User) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash

      module Codec
        extend T::Sig
        extend T::Generic
        extend ::Oapi::Codec::Contract

        Value = type_template { { fixed: KitchenSink::Types::User } }

        sig { override.params(value: T.untyped).returns(KitchenSink::Types::User) }
        def self.from_wire(value)
          raw = ::Oapi::Decode.object(value)
          KitchenSink::Types::User.new(
            id: ::Oapi::Decode.field(raw, "id") { |v| ::Oapi::Codec::Uuid.from_wire(v) },
            name: ::Oapi::Decode.field(raw, "name") { |v| ::Oapi::Codec::String.from_wire(v) },
            friend: ::Oapi::Decode.optional(raw, "friend") { |v| KitchenSink::Types::User::Codec.from_wire(v) },
          )
        end

        sig { override.params(value: KitchenSink::Types::User).returns(::Oapi::Wire) }
        def self.to_wire(value)
          wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
          wire["id"] = ::Oapi::Codec::Uuid.to_wire(value.id)
          wire["name"] = ::Oapi::Codec::String.to_wire(value.name)
          friend = value.friend
          wire["friend"] = KitchenSink::Types::User::Codec.to_wire(friend) unless friend.nil?
          wire
        end
      end
    end
  end
end
