# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class User < T::Struct
      extend T::Sig

      const :id, ::String
      const :name, ::String
      const :friend, T.nilable(KitchenSink::Types::User)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(User) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash
    end
  end
end
