# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Container
    extend T::Sig

    HANDLERS = T.let(
      {
      }.freeze,
      T::Hash[::String, T::Module[T.anything]]
    )

    sig { params(container: T.untyped).void }
    def self.verify!(container) = ::Oapi::Container.verify!(container, HANDLERS)
  end
end
