# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Demo
  module V1
    module Types
      class ModStatus < T::Enum
        enums do
          Live = new("live")
          UnderModeration = new("under-moderation")
          Hidden = new("hidden")
        end
      end

      class User < T::Struct
        extend T::Sig

        const :id, ::String
        const :name, ::String
        const :friend, T.nilable(Demo::V1::Types::User)

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(User)

          other.id == id &&
          other.name == name &&
          other.friend == friend
        end
      end

      class ModMeta < T::Struct
        extend T::Sig

        const :note, T.nilable(::String)

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(ModMeta)

          other.note == note
        end
      end

      class Mod < T::Struct
        extend T::Sig

        const :id, ::Integer
        const :name, ::String
        const :status, T.nilable(Demo::V1::Types::ModStatus)
        const :updated_at, ::Time
        const :deleted_at, T.nilable(::Time)
        const :summary, T.nilable(::String)
        const :bio, ::Oapi::Optional[T.nilable(::String)], factory: -> { ::Oapi::Absent.new }
        const :page_size, ::Integer, default: 20
        const :owner, ::Oapi::Optional[T.nilable(Demo::V1::Types::User)], factory: -> { ::Oapi::Absent.new }
        const :tags, T.nilable(T::Array[::String])
        const :meta, T.nilable(Demo::V1::Types::ModMeta)
        const :extra, T.nilable(T::Hash[::String, ::Integer])

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(Mod)

          other.id == id &&
          other.name == name &&
          other.status == status &&
          other.updated_at == updated_at &&
          other.deleted_at == deleted_at &&
          other.summary == summary &&
          other.bio == bio &&
          other.page_size == page_size &&
          other.owner == owner &&
          other.tags == tags &&
          other.meta == meta &&
          other.extra == extra
        end
      end

      class Cat < T::Struct
        extend T::Sig

        const :kind, ::String
        const :lives, T.nilable(::Integer)

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(Cat)

          other.kind == kind &&
          other.lives == lives
        end
      end

      class Dog < T::Struct
        extend T::Sig

        const :kind, ::String
        const :breed, T.nilable(::String)

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(Dog)

          other.kind == kind &&
          other.breed == breed
        end
      end

      Pet = T.type_alias { T.any(Demo::V1::Types::Cat, Demo::V1::Types::Dog) }

      Loose = T.type_alias { T.any(::String, ::Integer) }
    end

    module Codecs
      class ModStatusCodec
        extend T::Sig
        extend T::Generic
        include ::Oapi::Codec

        Value = type_member { { fixed: Demo::V1::Types::ModStatus } }

        VALUES = T.let(["live", "under-moderation", "hidden"].freeze, T::Array[::Oapi::Wire])

        sig { override.params(value: ::Oapi::Wire).returns(Demo::V1::Types::ModStatus) }
        def from_wire(value)
          Demo::V1::Types::ModStatus.try_deserialize(value) ||
            raise(::Oapi::DecodeError.new("expected one of #{VALUES.join(", ")}, got #{value.inspect}"))
        end

        sig { override.params(value: Demo::V1::Types::ModStatus).returns(::Oapi::Wire) }
        def to_wire(value) = value.serialize
      end
      ModStatus = T.let(ModStatusCodec.new, ModStatusCodec)

      class UserCodec
        extend T::Sig
        extend T::Generic
        include ::Oapi::Codec

        Value = type_member { { fixed: Demo::V1::Types::User } }

        sig { override.params(value: ::Oapi::Wire).returns(Demo::V1::Types::User) }
        def from_wire(value)
          raw = ::Oapi::Decode.object(value)
          Demo::V1::Types::User.new(
            id: ::Oapi::Decode.field(raw, "id") { |v| ::Oapi::Codec::Scalar::Uuid.from_wire(v) },
            name: ::Oapi::Decode.field(raw, "name") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
            friend: ::Oapi::Decode.optional(raw, "friend") { |v| Demo::V1::Codecs::User.from_wire(v) },
          )
        end

        sig { override.params(value: Demo::V1::Types::User).returns(::Oapi::Wire) }
        def to_wire(value)
          wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
          wire["id"] = ::Oapi::Codec::Scalar::Uuid.to_wire(value.id)
          wire["name"] = ::Oapi::Codec::Scalar::String.to_wire(value.name)
          friend = value.friend
          wire["friend"] = Demo::V1::Codecs::User.to_wire(friend) unless friend.nil?
          wire
        end
      end
      User = T.let(UserCodec.new, UserCodec)

      class ModMetaCodec
        extend T::Sig
        extend T::Generic
        include ::Oapi::Codec

        Value = type_member { { fixed: Demo::V1::Types::ModMeta } }

        sig { override.params(value: ::Oapi::Wire).returns(Demo::V1::Types::ModMeta) }
        def from_wire(value)
          raw = ::Oapi::Decode.object(value)
          Demo::V1::Types::ModMeta.new(
            note: ::Oapi::Decode.optional(raw, "note") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
          )
        end

        sig { override.params(value: Demo::V1::Types::ModMeta).returns(::Oapi::Wire) }
        def to_wire(value)
          wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
          note = value.note
          wire["note"] = ::Oapi::Codec::Scalar::String.to_wire(note) unless note.nil?
          wire
        end
      end
      ModMeta = T.let(ModMetaCodec.new, ModMetaCodec)

      class ModCodec
        extend T::Sig
        extend T::Generic
        include ::Oapi::Codec

        Value = type_member { { fixed: Demo::V1::Types::Mod } }

        sig { override.params(value: ::Oapi::Wire).returns(Demo::V1::Types::Mod) }
        def from_wire(value)
          raw = ::Oapi::Decode.object(value)
          Demo::V1::Types::Mod.new(
            id: ::Oapi::Decode.field(raw, "id") { |v| ::Oapi::Codec::Scalar::Integer.from_wire(v) },
            name: ::Oapi::Decode.field(raw, "name") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
            status: ::Oapi::Decode.optional(raw, "status") { |v| Demo::V1::Codecs::ModStatus.from_wire(v) },
            updated_at: ::Oapi::Decode.field(raw, "updatedAt") { |v| ::Oapi::Codec::Scalar::DateTime.from_wire(v) },
            deleted_at: ::Oapi::Decode.nullable_field(raw, "deletedAt") { |v| ::Oapi::Codec::Scalar::DateTime.from_wire(v) },
            summary: ::Oapi::Decode.optional(raw, "summary") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
            bio: ::Oapi::Decode.tristate(raw, "bio") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
            page_size: ::Oapi::Decode.defaulted(raw, "pageSize", 20) { |v| ::Oapi::Codec::Scalar::Integer.from_wire(v) },
            owner: ::Oapi::Decode.tristate(raw, "owner") { |v| Demo::V1::Codecs::User.from_wire(v) },
            tags: ::Oapi::Decode.optional(raw, "tags") { |v| Oapi::Decode.each(v) { |item| ::Oapi::Codec::Scalar::String.from_wire(item) } },
            meta: ::Oapi::Decode.optional(raw, "meta") { |v| Demo::V1::Codecs::ModMeta.from_wire(v) },
            extra: ::Oapi::Decode.optional(raw, "extra") { |v| Oapi::Decode.values(v) { |item| ::Oapi::Codec::Scalar::Integer.from_wire(item) } },
          )
        end

        sig { override.params(value: Demo::V1::Types::Mod).returns(::Oapi::Wire) }
        def to_wire(value)
          wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
          wire["id"] = ::Oapi::Codec::Scalar::Integer.to_wire(value.id)
          wire["name"] = ::Oapi::Codec::Scalar::String.to_wire(value.name)
          status = value.status
          wire["status"] = Demo::V1::Codecs::ModStatus.to_wire(status) unless status.nil?
          wire["updatedAt"] = ::Oapi::Codec::Scalar::DateTime.to_wire(value.updated_at)
          deleted_at = value.deleted_at
          wire["deletedAt"] = deleted_at.nil? ? nil : ::Oapi::Codec::Scalar::DateTime.to_wire(deleted_at)
          summary = value.summary
          wire["summary"] = ::Oapi::Codec::Scalar::String.to_wire(summary) unless summary.nil?
          bio = value.bio
          if bio.is_a?(::Oapi::Present)
            inner = bio.value
            wire["bio"] = inner.nil? ? nil : ::Oapi::Codec::Scalar::String.to_wire(inner)
          end
          page_size = value.page_size
          wire["pageSize"] = ::Oapi::Codec::Scalar::Integer.to_wire(page_size) unless page_size.nil?
          owner = value.owner
          if owner.is_a?(::Oapi::Present)
            inner = owner.value
            wire["owner"] = inner.nil? ? nil : Demo::V1::Codecs::User.to_wire(inner)
          end
          tags = value.tags
          wire["tags"] = tags.map { |item| ::Oapi::Codec::Scalar::String.to_wire(item) } unless tags.nil?
          meta = value.meta
          wire["meta"] = Demo::V1::Codecs::ModMeta.to_wire(meta) unless meta.nil?
          extra = value.extra
          wire["extra"] = extra.transform_values { |item| ::Oapi::Codec::Scalar::Integer.to_wire(item) } unless extra.nil?
          wire
        end
      end
      Mod = T.let(ModCodec.new, ModCodec)

      class CatCodec
        extend T::Sig
        extend T::Generic
        include ::Oapi::Codec

        Value = type_member { { fixed: Demo::V1::Types::Cat } }

        sig { override.params(value: ::Oapi::Wire).returns(Demo::V1::Types::Cat) }
        def from_wire(value)
          raw = ::Oapi::Decode.object(value)
          Demo::V1::Types::Cat.new(
            kind: ::Oapi::Decode.field(raw, "kind") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
            lives: ::Oapi::Decode.optional(raw, "lives") { |v| ::Oapi::Codec::Scalar::Integer.from_wire(v) },
          )
        end

        sig { override.params(value: Demo::V1::Types::Cat).returns(::Oapi::Wire) }
        def to_wire(value)
          wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
          wire["kind"] = ::Oapi::Codec::Scalar::String.to_wire(value.kind)
          lives = value.lives
          wire["lives"] = ::Oapi::Codec::Scalar::Integer.to_wire(lives) unless lives.nil?
          wire
        end
      end
      Cat = T.let(CatCodec.new, CatCodec)

      class DogCodec
        extend T::Sig
        extend T::Generic
        include ::Oapi::Codec

        Value = type_member { { fixed: Demo::V1::Types::Dog } }

        sig { override.params(value: ::Oapi::Wire).returns(Demo::V1::Types::Dog) }
        def from_wire(value)
          raw = ::Oapi::Decode.object(value)
          Demo::V1::Types::Dog.new(
            kind: ::Oapi::Decode.field(raw, "kind") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
            breed: ::Oapi::Decode.optional(raw, "breed") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
          )
        end

        sig { override.params(value: Demo::V1::Types::Dog).returns(::Oapi::Wire) }
        def to_wire(value)
          wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
          wire["kind"] = ::Oapi::Codec::Scalar::String.to_wire(value.kind)
          breed = value.breed
          wire["breed"] = ::Oapi::Codec::Scalar::String.to_wire(breed) unless breed.nil?
          wire
        end
      end
      Dog = T.let(DogCodec.new, DogCodec)

      class PetCodec
        extend T::Sig
        extend T::Generic
        include ::Oapi::Codec

        Value = type_member { { fixed: Demo::V1::Types::Pet } }

        TAGS = T.let(["cat", "dog"].freeze, T::Array[::String])

        sig { override.params(value: ::Oapi::Wire).returns(Demo::V1::Types::Pet) }
        def from_wire(value)
          raw = ::Oapi::Decode.object(value)
          tag = raw["kind"]
          case tag
          when "cat" then Demo::V1::Codecs::Cat.from_wire(raw)
          when "dog" then Demo::V1::Codecs::Dog.from_wire(raw)
          else raise(::Oapi::DecodeError.new("expected kind to be one of #{TAGS.join(", ")}, got #{tag.inspect}"))
          end
        end

        sig { override.params(value: Demo::V1::Types::Pet).returns(::Oapi::Wire) }
        def to_wire(value)
          case value
          when Demo::V1::Types::Cat then Demo::V1::Codecs::Cat.to_wire(value)
          when Demo::V1::Types::Dog then Demo::V1::Codecs::Dog.to_wire(value)
          else T.absurd(value)
          end
        end
      end
      Pet = T.let(PetCodec.new, PetCodec)

      class LooseCodec
        extend T::Sig
        extend T::Generic
        include ::Oapi::Codec

        Value = type_member { { fixed: Demo::V1::Types::Loose } }

        sig { override.params(value: ::Oapi::Wire).returns(Demo::V1::Types::Loose) }
        def from_wire(value)
          ::Oapi::Decode.first_of(value, "Loose", [
            ->(candidate) { ::Oapi::Codec::Scalar::String.from_wire(candidate) },
            ->(candidate) { ::Oapi::Codec::Scalar::Integer.from_wire(candidate) },
          ])
        end

        sig { override.params(value: Demo::V1::Types::Loose).returns(::Oapi::Wire) }
        def to_wire(value)
          case value
          when ::String then ::Oapi::Codec::Scalar::String.to_wire(value)
          when ::Integer then ::Oapi::Codec::Scalar::Integer.to_wire(value)
          else T.absurd(value)
          end
        end
      end
      Loose = T.let(LooseCodec.new, LooseCodec)
    end
  end
end
