# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Types
    class ModStatus < T::Enum
      enums do
        Live = new("live")
        UnderModeration = new("under-moderation")
        Hidden = new("hidden")
      end
    end

    class User < T::Struct
      extend T::Sig

      const :id, ::String
      const :name, ::String
      const :friend, T.nilable(KitchenSink::Types::User)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(User) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash
    end

    class ModMeta < T::Struct
      extend T::Sig

      const :note, T.nilable(::String)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(ModMeta) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash
    end

    class Mod < T::Struct
      extend T::Sig

      const :id, ::Integer
      const :name, ::String
      const :status, T.nilable(KitchenSink::Types::ModStatus)
      const :updated_at, ::Time
      const :deleted_at, T.nilable(::Time)
      const :summary, T.nilable(::String)
      const :bio, ::Oapi::Optional[T.nilable(::String)], factory: -> { ::Oapi::Absent.new }
      const :page_size, ::Integer, default: 20
      const :owner, ::Oapi::Optional[T.nilable(KitchenSink::Types::User)], factory: -> { ::Oapi::Absent.new }
      const :tags, T.nilable(T::Array[::String])
      const :meta, T.nilable(KitchenSink::Types::ModMeta)
      const :extra, T.nilable(T::Hash[::String, ::Integer])

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(Mod) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash
    end

    class Cat < T::Struct
      extend T::Sig

      const :kind, ::String
      const :lives, T.nilable(::Integer)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(Cat) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash
    end

    class Dog < T::Struct
      extend T::Sig

      const :kind, ::String
      const :breed, T.nilable(::String)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(Dog) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash
    end

    Pet = T.type_alias { T.any(KitchenSink::Types::Cat, KitchenSink::Types::Dog) }

    Loose = T.type_alias { T.any(::String, ::Integer) }
  end

  module Codecs
    class ModStatusCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::ModStatus } }

      VALUES = T.let(["live", "under-moderation", "hidden"].freeze, T::Array[::Oapi::Wire])

      sig { override.params(value: ::Oapi::Wire).returns(KitchenSink::Types::ModStatus) }
      def from_wire(value)
        KitchenSink::Types::ModStatus.try_deserialize(value) ||
          raise(::Oapi::DecodeError.new("expected one of #{VALUES.join(", ")}, got #{value.inspect}"))
      end

      sig { override.params(value: KitchenSink::Types::ModStatus).returns(::Oapi::Wire) }
      def to_wire(value) = value.serialize
    end
    ModStatus = T.let(ModStatusCodec.new, ModStatusCodec)

    class UserCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::User } }

      sig { override.params(value: ::Oapi::Wire).returns(KitchenSink::Types::User) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        KitchenSink::Types::User.new(
          id: ::Oapi::Decode.field(raw, "id") { |v| ::Oapi::Codec::Scalar::Uuid.from_wire(v) },
          name: ::Oapi::Decode.field(raw, "name") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
          friend: ::Oapi::Decode.optional(raw, "friend") { |v| KitchenSink::Codecs::User.from_wire(v) },
        )
      end

      sig { override.params(value: KitchenSink::Types::User).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        wire["id"] = ::Oapi::Codec::Scalar::Uuid.to_wire(value.id)
        wire["name"] = ::Oapi::Codec::Scalar::String.to_wire(value.name)
        friend = value.friend
        wire["friend"] = KitchenSink::Codecs::User.to_wire(friend) unless friend.nil?
        wire
      end
    end
    User = T.let(UserCodec.new, UserCodec)

    class ModMetaCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::ModMeta } }

      sig { override.params(value: ::Oapi::Wire).returns(KitchenSink::Types::ModMeta) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        KitchenSink::Types::ModMeta.new(
          note: ::Oapi::Decode.optional(raw, "note") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
        )
      end

      sig { override.params(value: KitchenSink::Types::ModMeta).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        note = value.note
        wire["note"] = ::Oapi::Codec::Scalar::String.to_wire(note) unless note.nil?
        wire
      end
    end
    ModMeta = T.let(ModMetaCodec.new, ModMetaCodec)

    class ModCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::Mod } }

      sig { override.params(value: ::Oapi::Wire).returns(KitchenSink::Types::Mod) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        KitchenSink::Types::Mod.new(
          id: ::Oapi::Decode.field(raw, "id") { |v| ::Oapi::Codec::Scalar::Integer.from_wire(v) },
          name: ::Oapi::Decode.field(raw, "name") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
          status: ::Oapi::Decode.optional(raw, "status") { |v| KitchenSink::Codecs::ModStatus.from_wire(v) },
          updated_at: ::Oapi::Decode.field(raw, "updatedAt") { |v| ::Oapi::Codec::Scalar::DateTime.from_wire(v) },
          deleted_at: ::Oapi::Decode.nullable_field(raw, "deletedAt") { |v| ::Oapi::Codec::Scalar::DateTime.from_wire(v) },
          summary: ::Oapi::Decode.optional(raw, "summary") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
          bio: ::Oapi::Decode.tristate(raw, "bio") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
          page_size: ::Oapi::Decode.defaulted(raw, "pageSize", 20) { |v| ::Oapi::Codec::Scalar::Integer.from_wire(v) },
          owner: ::Oapi::Decode.tristate(raw, "owner") { |v| KitchenSink::Codecs::User.from_wire(v) },
          tags: ::Oapi::Decode.optional(raw, "tags") { |v| Oapi::Decode.each(v) { |item| ::Oapi::Codec::Scalar::String.from_wire(item) } },
          meta: ::Oapi::Decode.optional(raw, "meta") { |v| KitchenSink::Codecs::ModMeta.from_wire(v) },
          extra: ::Oapi::Decode.optional(raw, "extra") { |v| Oapi::Decode.values(v) { |item| ::Oapi::Codec::Scalar::Integer.from_wire(item) } },
        )
      end

      sig { override.params(value: KitchenSink::Types::Mod).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        wire["id"] = ::Oapi::Codec::Scalar::Integer.to_wire(value.id)
        wire["name"] = ::Oapi::Codec::Scalar::String.to_wire(value.name)
        status = value.status
        wire["status"] = KitchenSink::Codecs::ModStatus.to_wire(status) unless status.nil?
        wire["updatedAt"] = ::Oapi::Codec::Scalar::DateTime.to_wire(value.updated_at)
        deleted_at = value.deleted_at
        wire["deletedAt"] = deleted_at.nil? ? nil : ::Oapi::Codec::Scalar::DateTime.to_wire(deleted_at)
        summary = value.summary
        wire["summary"] = ::Oapi::Codec::Scalar::String.to_wire(summary) unless summary.nil?
        bio = value.bio
        if bio.is_a?(::Oapi::Present)
          inner = bio.value
          wire["bio"] = inner.nil? ? nil : ::Oapi::Codec::Scalar::String.to_wire(inner)
        end
        page_size = value.page_size
        wire["pageSize"] = ::Oapi::Codec::Scalar::Integer.to_wire(page_size) unless page_size.nil?
        owner = value.owner
        if owner.is_a?(::Oapi::Present)
          inner = owner.value
          wire["owner"] = inner.nil? ? nil : KitchenSink::Codecs::User.to_wire(inner)
        end
        tags = value.tags
        wire["tags"] = tags.map { |item| ::Oapi::Codec::Scalar::String.to_wire(item) } unless tags.nil?
        meta = value.meta
        wire["meta"] = KitchenSink::Codecs::ModMeta.to_wire(meta) unless meta.nil?
        extra = value.extra
        wire["extra"] = extra.transform_values { |item| ::Oapi::Codec::Scalar::Integer.to_wire(item) } unless extra.nil?
        wire
      end
    end
    Mod = T.let(ModCodec.new, ModCodec)

    class CatCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::Cat } }

      sig { override.params(value: ::Oapi::Wire).returns(KitchenSink::Types::Cat) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        KitchenSink::Types::Cat.new(
          kind: ::Oapi::Decode.field(raw, "kind") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
          lives: ::Oapi::Decode.optional(raw, "lives") { |v| ::Oapi::Codec::Scalar::Integer.from_wire(v) },
        )
      end

      sig { override.params(value: KitchenSink::Types::Cat).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        wire["kind"] = ::Oapi::Codec::Scalar::String.to_wire(value.kind)
        lives = value.lives
        wire["lives"] = ::Oapi::Codec::Scalar::Integer.to_wire(lives) unless lives.nil?
        wire
      end
    end
    Cat = T.let(CatCodec.new, CatCodec)

    class DogCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::Dog } }

      sig { override.params(value: ::Oapi::Wire).returns(KitchenSink::Types::Dog) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        KitchenSink::Types::Dog.new(
          kind: ::Oapi::Decode.field(raw, "kind") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
          breed: ::Oapi::Decode.optional(raw, "breed") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
        )
      end

      sig { override.params(value: KitchenSink::Types::Dog).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        wire["kind"] = ::Oapi::Codec::Scalar::String.to_wire(value.kind)
        breed = value.breed
        wire["breed"] = ::Oapi::Codec::Scalar::String.to_wire(breed) unless breed.nil?
        wire
      end
    end
    Dog = T.let(DogCodec.new, DogCodec)

    class PetCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::Pet } }

      TAGS = T.let(["cat", "dog"].freeze, T::Array[::String])

      sig { override.params(value: ::Oapi::Wire).returns(KitchenSink::Types::Pet) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        tag = raw["kind"]
        case tag
        when "cat" then KitchenSink::Codecs::Cat.from_wire(raw)
        when "dog" then KitchenSink::Codecs::Dog.from_wire(raw)
        else raise(::Oapi::DecodeError.new("expected kind to be one of #{TAGS.join(", ")}, got #{tag.inspect}"))
        end
      end

      sig { override.params(value: KitchenSink::Types::Pet).returns(::Oapi::Wire) }
      def to_wire(value)
        case value
        when KitchenSink::Types::Cat then KitchenSink::Codecs::Cat.to_wire(value)
        when KitchenSink::Types::Dog then KitchenSink::Codecs::Dog.to_wire(value)
        else T.absurd(value)
        end
      end
    end
    Pet = T.let(PetCodec.new, PetCodec)

    class LooseCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::Loose } }

      sig { override.params(value: ::Oapi::Wire).returns(KitchenSink::Types::Loose) }
      def from_wire(value)
        ::Oapi::Decode.first_of(value, "Loose", [
          ->(candidate) { ::Oapi::Codec::Scalar::String.from_wire(candidate) },
          ->(candidate) { ::Oapi::Codec::Scalar::Integer.from_wire(candidate) },
        ])
      end

      sig { override.params(value: KitchenSink::Types::Loose).returns(::Oapi::Wire) }
      def to_wire(value)
        case value
        when ::String then ::Oapi::Codec::Scalar::String.to_wire(value)
        when ::Integer then ::Oapi::Codec::Scalar::Integer.to_wire(value)
        else T.absurd(value)
        end
      end
    end
    Loose = T.let(LooseCodec.new, LooseCodec)
  end
end
