# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Routes
    extend T::Sig

    sig { params(mapper: ::ActionDispatch::Routing::Mapper).void }
    def self.draw(mapper)
    end
  end
end
