# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Codecs
    class CatCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::Cat } }

      sig { override.params(value: T.untyped).returns(KitchenSink::Types::Cat) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        KitchenSink::Types::Cat.new(
          kind: ::Oapi::Decode.field(raw, "kind") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
          lives: ::Oapi::Decode.optional(raw, "lives") { |v| ::Oapi::Codec::Scalar::Integer.from_wire(v) },
        )
      end

      sig { override.params(value: KitchenSink::Types::Cat).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        wire["kind"] = ::Oapi::Codec::Scalar::String.to_wire(value.kind)
        lives = value.lives
        wire["lives"] = ::Oapi::Codec::Scalar::Integer.to_wire(lives) unless lives.nil?
        wire
      end
    end
    Cat = T.let(CatCodec.new, CatCodec)
  end
end
