# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Codecs
    class DogCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::Dog } }

      sig { override.params(value: T.untyped).returns(KitchenSink::Types::Dog) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        KitchenSink::Types::Dog.new(
          kind: ::Oapi::Decode.field(raw, "kind") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
          breed: ::Oapi::Decode.optional(raw, "breed") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
        )
      end

      sig { override.params(value: KitchenSink::Types::Dog).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        wire["kind"] = ::Oapi::Codec::Scalar::String.to_wire(value.kind)
        breed = value.breed
        wire["breed"] = ::Oapi::Codec::Scalar::String.to_wire(breed) unless breed.nil?
        wire
      end
    end
    Dog = T.let(DogCodec.new, DogCodec)
  end
end
