# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Codecs
    class LooseCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::Loose } }

      sig { override.params(value: T.untyped).returns(KitchenSink::Types::Loose) }
      def from_wire(value)
        ::Oapi::Decode.first_of(value, "Loose", [
          ->(candidate) { ::Oapi::Codec::Scalar::String.from_wire(candidate) },
          ->(candidate) { ::Oapi::Codec::Scalar::Integer.from_wire(candidate) },
        ])
      end

      sig { override.params(value: KitchenSink::Types::Loose).returns(::Oapi::Wire) }
      def to_wire(value)
        case value
        when ::String then ::Oapi::Codec::Scalar::String.to_wire(value)
        when ::Integer then ::Oapi::Codec::Scalar::Integer.to_wire(value)
        else T.absurd(value)
        end
      end
    end
    Loose = T.let(LooseCodec.new, LooseCodec)
  end
end
