# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Codecs
    class ModMetaCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::ModMeta } }

      sig { override.params(value: T.untyped).returns(KitchenSink::Types::ModMeta) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        KitchenSink::Types::ModMeta.new(
          note: ::Oapi::Decode.optional(raw, "note") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
        )
      end

      sig { override.params(value: KitchenSink::Types::ModMeta).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        note = value.note
        wire["note"] = ::Oapi::Codec::Scalar::String.to_wire(note) unless note.nil?
        wire
      end
    end
    ModMeta = T.let(ModMetaCodec.new, ModMetaCodec)
  end
end
