# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Codecs
    class PetCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::Pet } }

      TAGS = T.let(["cat", "dog"].freeze, T::Array[::String])

      sig { override.params(value: T.untyped).returns(KitchenSink::Types::Pet) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        tag = raw["kind"]
        case tag
        when "cat" then KitchenSink::Codecs::Cat.from_wire(raw)
        when "dog" then KitchenSink::Codecs::Dog.from_wire(raw)
        else raise(::Oapi::DecodeError.new("expected kind to be one of #{TAGS.join(", ")}, got #{tag.inspect}"))
        end
      end

      sig { override.params(value: KitchenSink::Types::Pet).returns(::Oapi::Wire) }
      def to_wire(value)
        case value
        when KitchenSink::Types::Cat then KitchenSink::Codecs::Cat.to_wire(value)
        when KitchenSink::Types::Dog then KitchenSink::Codecs::Dog.to_wire(value)
        else T.absurd(value)
        end
      end
    end
    Pet = T.let(PetCodec.new, PetCodec)
  end
end
