# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Codecs
    class SnakePet
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::SnakePet } }

      TAGS = T.let(["snake_cat", "snake_dog"].freeze, T::Array[::String])

      sig { override.params(value: T.untyped).returns(KitchenSink::Types::SnakePet) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        tag = raw["kind"]
        case tag
        when "snake_cat" then KitchenSink::Codecs::SnakeCat::INSTANCE.from_wire(raw)
        when "snake_dog" then KitchenSink::Codecs::SnakeDog::INSTANCE.from_wire(raw)
        else raise(::Oapi::DecodeError.new("expected kind to be one of #{TAGS.join(", ")}, got #{tag.inspect}"))
        end
      end

      sig { override.params(value: KitchenSink::Types::SnakePet).returns(::Oapi::Wire) }
      def to_wire(value)
        case value
        when KitchenSink::Types::SnakeCat then KitchenSink::Codecs::SnakeCat::INSTANCE.to_wire(value)
        when KitchenSink::Types::SnakeDog then KitchenSink::Codecs::SnakeDog::INSTANCE.to_wire(value)
        else T.absurd(value)
        end
      end

      INSTANCE = T.let(new, SnakePet)
    end
  end
end
