# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module KitchenSink
  module Codecs
    class SnakeDog
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: KitchenSink::Types::SnakeDog } }

      sig { override.params(value: T.untyped).returns(KitchenSink::Types::SnakeDog) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        KitchenSink::Types::SnakeDog.new(
          kind: ::Oapi::Decode.field(raw, "kind") { |v| ::Oapi::Codec::Primitive::String::INSTANCE.from_wire(v) },
        )
      end

      sig { override.params(value: KitchenSink::Types::SnakeDog).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        wire["kind"] = ::Oapi::Codec::Primitive::String::INSTANCE.to_wire(value.kind)
        wire
      end

      INSTANCE = T.let(new, SnakeDog)
    end
  end
end
