# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

require "oapi-runtime"

require_relative "types"
require_relative "operations"
require_relative "handlers"
require_relative "container"
