# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Operations
    module ListMods
      class Path < T::Struct
        extend T::Sig

        const :game_domain, ::String
      end

      class Query < T::Struct
        extend T::Sig

        const :page, ::Integer, default: 1
        const :status, T.nilable(Server::Types::ModStatus)
      end

      class Headers < T::Struct
        extend T::Sig

        const :application_name, T.nilable(::String)
      end

      class Request < T::Struct
        extend T::Sig

        const :path, Path
        const :query, Query
        const :headers, Headers
        const :http, ::ActionDispatch::Request
      end

      module Response
        extend T::Sig
        extend T::Helpers
        abstract!
        sealed!

        sig { abstract.returns(::Integer) }
        def status; end

        sig { abstract.returns(::Oapi::Wire) }
        def to_wire; end

        sig { abstract.returns(T.nilable(::String)) }
        def content_type; end
      end

      class Ok < T::Struct
        extend T::Sig
        include Response

        const :body, T::Array[Server::Types::Mod]

        sig { override.returns(::Integer) }
        def status = 200

        sig { override.returns(::Oapi::Wire) }
        def to_wire = body.map { |item| Server::Codecs::Mod.to_wire(item) }

        sig { override.returns(T.nilable(::String)) }
        def content_type = "application/json"
      end

      class BadRequest < T::Struct
        extend T::Sig
        include Response

        const :body, Server::Types::ProblemDetails

        sig { override.returns(::Integer) }
        def status = 400

        sig { override.returns(::Oapi::Wire) }
        def to_wire = Server::Codecs::ProblemDetails.to_wire(body)

        sig { override.returns(T.nilable(::String)) }
        def content_type = "application/problem+json"
      end
    end

    module CreateMod
      class Path < T::Struct
        extend T::Sig

        const :game_domain, ::String
      end

      class Request < T::Struct
        extend T::Sig

        const :path, Path
        const :body, Server::Types::NewMod
        const :http, ::ActionDispatch::Request
      end

      module Response
        extend T::Sig
        extend T::Helpers
        abstract!
        sealed!

        sig { abstract.returns(::Integer) }
        def status; end

        sig { abstract.returns(::Oapi::Wire) }
        def to_wire; end

        sig { abstract.returns(T.nilable(::String)) }
        def content_type; end
      end

      class Created < T::Struct
        extend T::Sig
        include Response

        const :body, Server::Types::Mod

        sig { override.returns(::Integer) }
        def status = 201

        sig { override.returns(::Oapi::Wire) }
        def to_wire = Server::Codecs::Mod.to_wire(body)

        sig { override.returns(T.nilable(::String)) }
        def content_type = "application/json"
      end

      class NoContent < T::Struct
        extend T::Sig
        include Response

        sig { override.returns(::Integer) }
        def status = 204

        sig { override.returns(::Oapi::Wire) }
        def to_wire = nil

        sig { override.returns(T.nilable(::String)) }
        def content_type = nil
      end

      class Default < T::Struct
        extend T::Sig
        include Response

        const :body, Server::Types::ProblemDetails
        const :status_code, ::Integer

        sig { override.returns(::Integer) }
        def status = status_code

        sig { override.returns(::Oapi::Wire) }
        def to_wire = Server::Codecs::ProblemDetails.to_wire(body)

        sig { override.returns(T.nilable(::String)) }
        def content_type = "application/problem+json"
      end
    end

    module GetHealth
      class Request < T::Struct
        extend T::Sig

        const :http, ::ActionDispatch::Request
      end

      module Response
        extend T::Sig
        extend T::Helpers
        abstract!
        sealed!

        sig { abstract.returns(::Integer) }
        def status; end

        sig { abstract.returns(::Oapi::Wire) }
        def to_wire; end

        sig { abstract.returns(T.nilable(::String)) }
        def content_type; end
      end

      class Ok < T::Struct
        extend T::Sig
        include Response

        sig { override.returns(::Integer) }
        def status = 200

        sig { override.returns(::Oapi::Wire) }
        def to_wire = nil

        sig { override.returns(T.nilable(::String)) }
        def content_type = nil
      end
    end
  end
end
