# Generated by openapi_kit. Do not edit. https://github.com/Nexus-Mods/openapi_kit
# typed: strict
# frozen_string_literal: true

module Server
  extend T::Sig

  @registry = T.let(nil, T.nilable(Registry))

  sig { params(registry: Registry).void }
  def self.registry=(registry)
    @registry = registry
  end

  sig { returns(Registry) }
  def self.registry
    @registry || raise(
      "Server.registry has not been assigned. Build one in an initializer, " \
      "e.g. Server.registry = Server::Registry.new(...)."
    )
  end
end
