# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Types
    class ModStatus < T::Enum
      enums do
        Live = new("live")
        Hidden = new("hidden")
      end
    end

    class Mod < T::Struct
      extend T::Sig

      const :id, ::Integer
      const :name, ::String
      const :status, T.nilable(Server::Types::ModStatus)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(Mod) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash
    end

    class ProblemDetails < T::Struct
      extend T::Sig

      const :title, ::String
      const :detail, T.nilable(::String)

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(ProblemDetails) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash
    end

    class NewMod < T::Struct
      extend T::Sig

      const :name, ::String

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other) = other.instance_of?(NewMod) && other.serialize == serialize

      sig { params(other: T.untyped).returns(T::Boolean) }
      def eql?(other) = self == other

      sig { returns(::Integer) }
      def hash = [self.class, serialize].hash
    end
  end

  module Codecs
    class ModStatusCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: Server::Types::ModStatus } }

      VALUES = T.let(["live", "hidden"].freeze, T::Array[::Oapi::Wire])

      sig { override.params(value: ::Oapi::Wire).returns(Server::Types::ModStatus) }
      def from_wire(value)
        Server::Types::ModStatus.try_deserialize(value) ||
          raise(::Oapi::DecodeError.new("expected one of #{VALUES.join(", ")}, got #{value.inspect}"))
      end

      sig { override.params(value: Server::Types::ModStatus).returns(::Oapi::Wire) }
      def to_wire(value) = value.serialize
    end
    ModStatus = T.let(ModStatusCodec.new, ModStatusCodec)

    class ModCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: Server::Types::Mod } }

      sig { override.params(value: ::Oapi::Wire).returns(Server::Types::Mod) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        Server::Types::Mod.new(
          id: ::Oapi::Decode.field(raw, "id") { |v| ::Oapi::Codec::Scalar::Integer.from_wire(v) },
          name: ::Oapi::Decode.field(raw, "name") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
          status: ::Oapi::Decode.optional(raw, "status") { |v| Server::Codecs::ModStatus.from_wire(v) },
        )
      end

      sig { override.params(value: Server::Types::Mod).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        wire["id"] = ::Oapi::Codec::Scalar::Integer.to_wire(value.id)
        wire["name"] = ::Oapi::Codec::Scalar::String.to_wire(value.name)
        status = value.status
        wire["status"] = Server::Codecs::ModStatus.to_wire(status) unless status.nil?
        wire
      end
    end
    Mod = T.let(ModCodec.new, ModCodec)

    class ProblemDetailsCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: Server::Types::ProblemDetails } }

      sig { override.params(value: ::Oapi::Wire).returns(Server::Types::ProblemDetails) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        Server::Types::ProblemDetails.new(
          title: ::Oapi::Decode.field(raw, "title") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
          detail: ::Oapi::Decode.optional(raw, "detail") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
        )
      end

      sig { override.params(value: Server::Types::ProblemDetails).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        wire["title"] = ::Oapi::Codec::Scalar::String.to_wire(value.title)
        detail = value.detail
        wire["detail"] = ::Oapi::Codec::Scalar::String.to_wire(detail) unless detail.nil?
        wire
      end
    end
    ProblemDetails = T.let(ProblemDetailsCodec.new, ProblemDetailsCodec)

    class NewModCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: Server::Types::NewMod } }

      sig { override.params(value: ::Oapi::Wire).returns(Server::Types::NewMod) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        Server::Types::NewMod.new(
          name: ::Oapi::Decode.field(raw, "name") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
        )
      end

      sig { override.params(value: Server::Types::NewMod).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        wire["name"] = ::Oapi::Codec::Scalar::String.to_wire(value.name)
        wire
      end
    end
    NewMod = T.let(NewModCodec.new, NewModCodec)
  end
end
