# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Codecs
    class Mod
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: Server::Types::Mod } }

      sig { override.params(value: T.untyped).returns(Server::Types::Mod) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        Server::Types::Mod.new(
          id: ::Oapi::Decode.field(raw, "id") { |v| ::Oapi::Codec::Primitive::Integer::INSTANCE.from_wire(v) },
          name: ::Oapi::Decode.field(raw, "name") { |v| ::Oapi::Codec::Primitive::String::INSTANCE.from_wire(v) },
          status: ::Oapi::Decode.optional(raw, "status") { |v| Server::Codecs::ModStatus::INSTANCE.from_wire(v) },
        )
      end

      sig { override.params(value: Server::Types::Mod).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        wire["id"] = ::Oapi::Codec::Primitive::Integer::INSTANCE.to_wire(value.id)
        wire["name"] = ::Oapi::Codec::Primitive::String::INSTANCE.to_wire(value.name)
        status = value.status
        wire["status"] = Server::Codecs::ModStatus::INSTANCE.to_wire(status) unless status.nil?
        wire
      end

      INSTANCE = T.let(new, Mod)
    end
  end
end
