# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Codecs
    class NewModCodec
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: Server::Types::NewMod } }

      sig { override.params(value: T.untyped).returns(Server::Types::NewMod) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        Server::Types::NewMod.new(
          name: ::Oapi::Decode.field(raw, "name") { |v| ::Oapi::Codec::Scalar::String.from_wire(v) },
        )
      end

      sig { override.params(value: Server::Types::NewMod).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        wire["name"] = ::Oapi::Codec::Scalar::String.to_wire(value.name)
        wire
      end
    end
    NewMod = T.let(NewModCodec.new, NewModCodec)
  end
end
