# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi
# typed: strict
# frozen_string_literal: true

module Server
  module Codecs
    class ProblemDetails
      extend T::Sig
      extend T::Generic
      include ::Oapi::Codec

      Value = type_member { { fixed: Server::Types::ProblemDetails } }

      sig { override.params(value: T.untyped).returns(Server::Types::ProblemDetails) }
      def from_wire(value)
        raw = ::Oapi::Decode.object(value)
        Server::Types::ProblemDetails.new(
          title: ::Oapi::Decode.field(raw, "title") { |v| ::Oapi::Codec::Primitive::String::INSTANCE.from_wire(v) },
          detail: ::Oapi::Decode.optional(raw, "detail") { |v| ::Oapi::Codec::Primitive::String::INSTANCE.from_wire(v) },
        )
      end

      sig { override.params(value: Server::Types::ProblemDetails).returns(::Oapi::Wire) }
      def to_wire(value)
        wire = T.let({}, T::Hash[::String, ::Oapi::Wire])
        wire["title"] = ::Oapi::Codec::Primitive::String::INSTANCE.to_wire(value.title)
        detail = value.detail
        wire["detail"] = ::Oapi::Codec::Primitive::String::INSTANCE.to_wire(detail) unless detail.nil?
        wire
      end

      INSTANCE = T.let(new, ProblemDetails)
    end
  end
end
