# typed: strict
# frozen_string_literal: true

require "oapi/runtime"

require "oapi/codegen/naming"
require "oapi/codegen/ruby_type"
require "oapi/codegen/ir/schema"
require "oapi/codegen/ir/type_def"
require "oapi/codegen/ir/document"
require "oapi/codegen/type_registry"
require "oapi/codegen/config"
require "oapi/codegen/writer"
require "oapi/codegen/loader"
require "oapi/codegen/emit/buffer"
require "oapi/codegen/emit/source_file"
require "oapi/codegen/emit/literal"
require "oapi/codegen/emit/types"
require "oapi/codegen/emit/codecs"
require "oapi/codegen/emit/operations"
require "oapi/codegen/emit/handlers"
require "oapi/codegen/emit/container"
require "oapi/codegen/generator"
require "oapi/codegen/cli"

module Oapi
  module Codegen
    MARKER = "# Generated by oapi. Do not edit. https://github.com/Nexus-Mods/oapi"
  end
end
