# typed: strict
# frozen_string_literal: true

require "fileutils"
require "pathname"
require "prism"

module Oapi
  module Codegen
    class Writer
      extend T::Sig

      sig { returns(Pathname) }
      attr_reader :output

      sig { returns(T::Array[Pathname]) }
      attr_reader :written

      sig { params(output: Pathname).void }
      def initialize(output:)
        @output = output
        @written = T.let([], T::Array[Pathname])
      end

      sig { void }
      def clean!
        return unless output.directory?

        existing = output.glob("**/*.rb").sort
        foreign = existing.reject { |path| path.read.start_with?(MARKER) }
        unless foreign.empty?
          raise Error,
                "Refusing to clean #{output}: #{foreign.size} file#{"s" if foreign.size > 1} " \
                "not generated by oapi (#{foreign.first(3).map { |f| f.relative_path_from(output) }.join(", ")}" \
                "#{"…" if foreign.size > 3}). Point `output` at a directory oapi owns."
        end

        existing.each(&:delete)
      end

      sig { params(name: String, content: String).returns(Pathname) }
      def write(name, content)
        verify_syntax!(name, content)
        path = output.join(name)
        FileUtils.mkdir_p(path.dirname)
        body = content.end_with?("\n") ? content : "#{content}\n"
        path.write("#{MARKER}\n#{body}")
        @written << path
        path
      end

      private

      sig { params(name: String, content: String).void }
      def verify_syntax!(name, content)
        result = Prism.parse(content)
        return if result.success?

        error = T.must(result.errors.first)
        line = error.location.start_line
        raise Error,
              "oapi generated invalid Ruby in #{name} at line #{line}: #{error.message}\n  " \
              "#{content.lines[line - 1]&.strip}\n" \
              "This is a bug in oapi, not in your schema. Please report it."
      end
    end
  end
end
