# typed: strict
# frozen_string_literal: true

require "fileutils"
require "pathname"
require "prism"

module Oapi
  module Codegen
    class Writer
      extend T::Sig

      sig { params(output: Pathname).void }
      def initialize(output:)
        @output = output
      end

      sig { void }
      def clean!
        return unless output.directory?

        existing = output.glob("**/*.rb").sort
        foreign = existing.reject { |path| path.read.start_with?(MARKER) }
        unless foreign.empty?
          raise Error,
                "Refusing to clean #{output}: #{foreign.size} file#{"s" if foreign.size > 1} " \
                "not generated by oapi (#{foreign.first(3).map { |f| f.relative_path_from(output) }.join(", ")}" \
                "#{"…" if foreign.size > 3}). Point `output` at a directory oapi owns."
        end

        existing.each(&:delete)
        prune_empty_directories
      end

      sig { params(files: T::Array[Emit::SourceFile]).returns(T::Array[Pathname]) }
      def write_all(files)
        files.each { |file| verify_syntax!(file.path, file.contents) }
        reject_duplicate_paths!(files)

        clean!
        files.map { |file| write(file.path, file.contents) }
      end

      sig { params(name: String, content: String).returns(Pathname) }
      def write(name, content)
        verify_syntax!(name, content)
        path = output.join(name)
        FileUtils.mkdir_p(path.dirname)
        body = content.end_with?("\n") ? content : "#{content}\n"
        path.write("#{MARKER}\n#{body}")
        path
      end

      private

      sig { returns(Pathname) }
      attr_reader :output

      sig { params(files: T::Array[Emit::SourceFile]).void }
      def reject_duplicate_paths!(files)
        duplicates = files.group_by(&:path).select { |_, group| group.size > 1 }
        return if duplicates.empty?

        raise Error,
              "oapi generated more than one file for #{duplicates.keys.sort.join(", ")}. " \
              "Two names in your document normalise to the same constant. " \
              "Disambiguate them, or set name_overrides in your config."
      end

      sig { void }
      def prune_empty_directories
        output.glob("**/*").select(&:directory?).sort.reverse_each do |directory|
          directory.rmdir if directory.children.empty?
        end
      end

      sig { params(name: String, content: String).void }
      def verify_syntax!(name, content)
        result = Prism.parse(content)
        return if result.success?

        error = T.must(result.errors.first)
        line = error.location.start_line
        raise Error,
              "oapi generated invalid Ruby in #{name} at line #{line}: #{error.message}\n  " \
              "#{content.lines[line - 1]&.strip}\n" \
              "This is a bug in oapi, not in your schema. Please report it."
      end
    end
  end
end
